import { createApp, defineComponent, h, onMounted, ref } from "vue";

type Payload = { industry: string; generatedAt: number; profile: { availability: string; reason: string | null; items: Array<{ industryProfileId: string; industryName: string; taxonomy: string; taxonomyVersion: string; version: number; definition: string; demandDrivers: unknown[]; supplyStructure: Record<string, unknown>; cycleCharacteristics: Record<string, unknown>; valueChain: unknown[]; sourceReferences: Array<{ url?: string; title?: string }> }> }; typedProfiles: { availability: string; reason: string | null; items: Array<{ trackProfileId: string; industryName: string; taxonomy: string; taxonomyVersion: string; version: number; boundaryIncluded: string; boundaryExcluded: string; demandEquation: string | null; supplyEquation: string | null; cyclePosition: string; valuationPrimaryMethod: string | null; valuationLimitations: string | null; demandDrivers: Array<{ label: string; financialTransmission: string }>; supplyConstraints: Array<{ label: string; affectedVariable: string }>; kpis: Array<{ name: string; financialMapping: string }>; sourceReferences: Array<{ url?: string; title?: string }> }> }; assessment: { state: string; summary: string; nextSteps: string[] }; evidence: Array<{ evidenceId: string; title: string; url: string; publishedAt: number; sourceId: string; grade: string; eventStatus: string }>; impacts: Array<{ direction: string; transmission: string; confidence: number }>; sources: Array<{ sourceId: string; name: string; state: string; lastSuccessAt: number | null; lastError: string | null }> };
const style = `.industry-research{background:#f4f7f8;min-height:calc(100vh - 8rem);padding:1.25rem 0 2.5rem}.industry-card{background:#fff;border:1px solid #dbe7e5;border-radius:1rem;box-shadow:0 .5rem 1.3rem rgba(15,52,51,.05);padding:1rem}.industry-hero{background:linear-gradient(135deg,#112f43,#0f766e);color:#fff}.industry-hero h1{margin:.35rem 0}.industry-meta{color:#64748b;font-size:.84rem}.industry-badge{background:#e2e8f0;border-radius:99px;color:#334155;display:inline-block;font-size:.8rem;font-weight:700;padding:.25rem .6rem}.industry-list{padding-left:1.1rem}.industry-table{font-size:.88rem}.industry-table td,.industry-table th{vertical-align:top}`;
function selectedIndustry() { return new URLSearchParams(location.search).get("industry")?.trim() || ""; }
function displayDate(value: number) { return new Date(value).toLocaleString("zh-CN", { hour12: false }); }
const App = defineComponent({ setup() { const industry = ref(selectedIndustry()); const data = ref<Payload | null>(null); const loading = ref(false); const error = ref(""); const load = async () => { if (!industry.value.trim()) { error.value = "输入行业名称后读取现有可审计档案。"; return; } loading.value = true; error.value = ""; try { const r = await fetch(`/api/research/industry?industry=${encodeURIComponent(industry.value.trim())}`); const b = await r.json(); if (!r.ok || b.code !== 200) throw new Error(b.msg || "读取失败"); data.value = b.data; } catch (e) { error.value = e instanceof Error ? e.message : String(e); } finally { loading.value = false; } }; onMounted(() => { if (industry.value) void load(); }); return () => h("main", { class: "industry-research" }, [h("style", style), h("div", { class: "container", style: "max-width:1200px" }, [h("section", { class: "industry-card industry-hero" }, [h("div", { class: "small opacity-75" }, "AUDITABLE INDUSTRY DOSSIER"), h("h1", "行业研究档案"), h("p", { class: "mb-3 opacity-75" }, "只展示已入库的事实、冲突、来源健康和待验证任务；不会从行业故事推导交易指令。"), h("div", { class: "d-flex gap-2" }, [h("input", { class: "form-control", value: industry.value, placeholder: "例如：通信设备", onInput: (e: Event) => { industry.value = (e.target as HTMLInputElement).value; }, onKeyup: (e: KeyboardEvent) => { if (e.key === "Enter") void load(); } }), h("button", { class: "btn btn-light", onClick: () => void load() }, "读取")])]), loading.value ? h("div", { class: "industry-card mt-3 text-center text-muted" }, "读取中…") : error.value ? h("div", { class: "industry-card mt-3 text-danger" }, error.value) : data.value ? view(data.value) : h("div", { class: "industry-card mt-3 text-muted" }, "输入行业名称，查看当前可审计档案。")])]); } });
function view(data: Payload) {
  const support = data.impacts.filter((item) => item.direction === "support").length;
  const pressure = data.impacts.filter((item) => item.direction === "pressure").length;
  const evidenceRows = data.evidence.map((item) => h("tr", { key: item.evidenceId }, [
    h("td", [h("a", { href: item.url, target: "_blank", rel: "noreferrer" }, item.title)]),
    h("td", `${item.grade} / ${item.eventStatus}`), h("td", `${item.sourceId} · ${displayDate(item.publishedAt)}`),
  ]));
  const evidence = evidenceRows.length ? h("div", { class: "table-responsive" }, h("table", { class: "table table-sm industry-table" }, [h("thead", h("tr", [h("th", "证据"), h("th", "等级"), h("th", "来源")])), h("tbody", evidenceRows)])) : h("p", { class: "text-muted small" }, "暂无精确关联证据。");
  const profiles = data.profile?.items || [];
  const profile = profiles.length ? h("section", { class: "industry-card mt-3" }, [
    h("div", { class: "d-flex justify-content-between align-items-start" }, [h("h2", "版本化行业 profile"), h("span", { class: "industry-badge" }, `${data.profile.availability} · ${profiles.length} 版`)]),
    ...profiles.map((item) => h("article", { class: "border-top pt-2 mt-2", key: item.industryProfileId }, [h("strong", `${item.industryName} · ${item.taxonomy} ${item.taxonomyVersion} · v${item.version}`), h("p", { class: "small mb-1" }, item.definition), h("div", { class: "industry-meta" }, `需求驱动：${item.demandDrivers.map(String).join("；") || "待补"}`), h("div", { class: "industry-meta" }, `价值链：${item.valueChain.map(String).join("；") || "待补"}`), item.sourceReferences.length ? h("ul", { class: "industry-list small mt-2 mb-0" }, item.sourceReferences.slice(0, 4).map((ref) => h("li", ref.url ? h("a", { href: ref.url, target: "_blank", rel: "noreferrer" }, ref.title || ref.url) : ref.title || "可追溯来源"))) : h("div", { class: "industry-meta" }, "来源待补")]))
  ]) : h("section", { class: "industry-card mt-3" }, [h("h2", "版本化行业 profile"), h("p", { class: "text-muted small mb-0" }, data.profile?.availability === "unavailable" ? `当前受阻：${data.profile.reason || "存储待初始化"}` : "尚无该行业 profile。行业标签、媒体主题或资金流不等同于可用于公司分析的赛道定义；需补主源、版本和引用。")]);
  const typedProfiles = data.typedProfiles?.items || [];
  const typedProfile = h("section", { class: "industry-card mt-3" }, [h("div", { class: "d-flex justify-content-between align-items-start" }, [h("h2", "字段化赛道 profile"), h("span", { class: "industry-badge" }, `${data.typedProfiles?.availability || "unavailable"} · ${typedProfiles.length} 版`)]), typedProfiles.length ? typedProfiles.map((item) => h("article", { class: "border-top pt-2 mt-2", key: item.trackProfileId }, [h("strong", `${item.industryName} · ${item.taxonomy} ${item.taxonomyVersion} · v${item.version}`), h("p", { class: "small mb-1" }, `边界：包含 ${item.boundaryIncluded}；排除 ${item.boundaryExcluded}`), h("div", { class: "industry-meta" }, `需求方程：${item.demandEquation || "待补"}；供给方程：${item.supplyEquation || "待补"}；周期：${item.cyclePosition}`), h("div", { class: "industry-meta" }, `需求驱动：${item.demandDrivers.map((driver) => `${driver.label}→${driver.financialTransmission}`).join("；") || "待补"}`), h("div", { class: "industry-meta" }, `KPI：${item.kpis.map((kpi) => `${kpi.name}→${kpi.financialMapping}`).join("；") || "待补"}`), item.sourceReferences.length ? h("ul", { class: "industry-list small mt-2 mb-0" }, item.sourceReferences.slice(0, 4).map((ref) => h("li", ref.url ? h("a", { href: ref.url, target: "_blank", rel: "noreferrer" }, ref.title || ref.url) : ref.title || "可追溯来源"))) : null])) : h("p", { class: "text-muted small mb-0" }, data.typedProfiles?.availability === "unavailable" ? `当前受阻：${data.typedProfiles.reason || "存储待初始化"}` : "尚无字段化赛道 profile。必须逐字段记录赛道边界、需求/供给方程、KPI 与财务传导，不能以主题标签替代。")]);
  const dossier = h("section", { class: "industry-card h-100" }, [
    h("div", { class: "d-flex justify-content-between" }, [h("h2", data.industry), h("span", { class: "industry-badge" }, data.assessment.state)]),
    h("p", data.assessment.summary), h("div", { class: "row small" }, [h("div", { class: "col-6" }, `支持影响 ${support} 条`), h("div", { class: "col-6" }, `压力影响 ${pressure} 条`)]), h("hr"), h("h3", { class: "h6" }, "原始证据"), evidence,
  ]);
  const sources = h("section", { class: "industry-card h-100" }, [
    h("h2", "待验证与来源健康"), h("ul", { class: "industry-list small" }, data.assessment.nextSteps.map((item) => h("li", item))), h("hr"),
    ...data.sources.map((item) => h("div", { class: "mb-2 small", key: item.sourceId }, [h("strong", item.name), h("div", { class: "industry-meta" }, `${item.state} · 最近成功 ${item.lastSuccessAt ? displayDate(item.lastSuccessAt) : "待补"}${item.lastError ? ` · ${item.lastError}` : ""}`)])),
  ]);
  return h("div", [h("div", { class: "row g-3 mt-1" }, [h("div", { class: "col-lg-7" }, [dossier]), h("div", { class: "col-lg-5" }, [sources])]), typedProfile, profile]);
}
const root = document.getElementById("industry-research-vue-root"); if (root) createApp(App).mount(root);
