import { defineComponent, h, onMounted, ref } from "vue";

type Candidate = { candidateId: string; statement: string; period: string | null; sourceUrl: string | null; contentUrl: string | null; title: string | null; sourceName: string | null; reusableEvidenceReference: { evidenceReferenceId: string } | null };
type Metric = { metricKey: string; label: string; valueKind: "ratio" | "amount"; normalizedUnit: string; requiresCurrency: boolean; requiresAmountScale: boolean; definitionRequirement: string; missingInput: string; state: "reported" | "missing" | "conflicting"; reason: string; fact: Fact | null; effectiveFacts: Fact[] };
type Fact = { financialSpecialtyFactId: string; reportedLabel: string; reportedValue: string; valueNumber: number; unit: string; currency: string | null; amountScale: string | null; asOf: string; periodLabel: string; definitionNote: string; comparabilityNote: string; sourceUrl: string | null; contentUrl: string | null; sourceTitle: string | null; sourceName: string | null; sourceLocator: string; evidenceReferenceId: string; financialProfileId: string };
type Ledger = { availability: string; status: "blocked_entity_profile" | "not_applicable" | "needs_sources" | "partial" | "conflicting" | "storage_unavailable"; entityType: string | null; entityLabel: string | null; reason: string; profile?: { asOf: string | null }; configVersion: string; metrics: Metric[]; facts: Fact[] };
type FinancialProfile = { status?: string; entityType?: string | null; asOf?: string | null; records?: Array<{ financialProfileId: string; entityType: string; asOf: string }> };
type Form = { evidenceReferenceId: string; metricKey: string; reportedLabel: string; reportedValue: string; valueNumber: string; currency: string; amountScale: string; asOf: string; periodLabel: string; definitionNote: string; comparabilityNote: string };
const empty = (): Form => ({ evidenceReferenceId: "", metricKey: "", reportedLabel: "", reportedValue: "", valueNumber: "", currency: "", amountScale: "", asOf: new Date().toISOString().slice(0, 10), periodLabel: "", definitionNote: "", comparabilityNote: "" });
const css = `.financial-specialty-metrics{border-left:4px solid #0f766e}.financial-specialty-metrics .specialty-item{border-top:1px solid #ccfbf1;padding:.75rem 0}.financial-specialty-metrics .specialty-item:first-of-type{border-top:0}.financial-specialty-metrics .specialty-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.55rem;padding:.7rem;margin-top:.7rem;background:#f0fdfa;border-radius:.6rem}.financial-specialty-metrics label{font-size:.79rem;color:#134e4a}.financial-specialty-metrics input,.financial-specialty-metrics select,.financial-specialty-metrics textarea{width:100%;margin-top:.2rem;border:1px solid #5eead4;border-radius:.4rem;padding:.4rem;background:#fff}.financial-specialty-metrics textarea{min-height:3.8rem}.financial-specialty-metrics .wide{grid-column:1/-1}.financial-specialty-metrics .fact-chain{font:normal .72rem ui-monospace,SFMono-Regular,Menlo,monospace;color:#475569;overflow-wrap:anywhere}@media(max-width:600px){.financial-specialty-metrics .specialty-form{grid-template-columns:1fr}}`;
const statusLabel: Record<string, string> = { blocked_entity_profile: "实体类型阻断", not_applicable: "不适用", needs_sources: "待来源", partial: "已录入部分来源", conflicting: "来源冲突", storage_unavailable: "账本未初始化" };

/** A reader/editor for source facts only.  It deliberately offers no score,
 * peer average, forecast, scenario, valuation or recommendation control. */
export const FinancialSpecialtyMetricsPanel = defineComponent({
  name: "FinancialSpecialtyMetricsPanel",
  props: { securityCode: { type: String, required: true }, initial: { type: Object, required: true }, financialProfile: { type: Object, required: true }, canWrite: { type: Boolean, required: true } },
  setup(props) {
    const ledger = ref<Ledger>(props.initial as Ledger); const profile = ref<FinancialProfile>(props.financialProfile as FinancialProfile); const candidates = ref<Candidate[]>([]); const form = ref<Form>(empty()); const loading = ref(false); const saving = ref(false); const error = ref(""); const notice = ref("");
    const endpoint = () => `/api/research/company/${encodeURIComponent(props.securityCode)}/financial-specialty-metrics`;
    const selectedMetric = () => ledger.value.metrics.find((item) => item.metricKey === form.value.metricKey) || null;
    const profileId = () => profile.value.records?.find((item) => item.entityType === ledger.value.entityType && item.asOf === profile.value.asOf)?.financialProfileId || "";
    const eligible = () => candidates.value.filter((item) => item.reusableEvidenceReference);
    const refresh = async () => { const response = await fetch(endpoint()); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "读取金融专属指标失败"); ledger.value = body.data; };
    const load = async () => {
      loading.value = true; error.value = "";
      try { await refresh(); if (props.canWrite) { const response = await fetch(`/api/research/company/${encodeURIComponent(props.securityCode)}/information-evidence-candidates`); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "读取已审核来源证据失败"); candidates.value = Array.isArray(body.data?.items) ? body.data.items : []; } }
      catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); }
      finally { loading.value = false; }
    };
    const chooseMetric = (metricKey: string) => { const metric = ledger.value.metrics.find((item) => item.metricKey === metricKey); form.value = { ...empty(), metricKey, asOf: ledger.value.profile?.asOf || new Date().toISOString().slice(0, 10), definitionNote: metric?.definitionRequirement || "", comparabilityNote: "仅按该来源直接披露记录；尚未与其他主体、期间或估值口径合并。" }; };
    const save = async () => {
      const metric = selectedMetric(); const financialProfileId = profileId(); const evidence = eligible().find((item) => item.reusableEvidenceReference?.evidenceReferenceId === form.value.evidenceReferenceId); const valueNumber = Number(form.value.valueNumber);
      if (!metric || !financialProfileId || !evidence?.reusableEvidenceReference) { error.value = "需选择当前确认的专属指标、当前实体分类来源和已接受的信息预处理证据。"; return; }
      if (!form.value.reportedLabel.trim() || !form.value.reportedValue.trim() || !Number.isFinite(valueNumber) || !form.value.asOf || !form.value.periodLabel.trim() || !form.value.definitionNote.trim() || !form.value.comparabilityNote.trim()) { error.value = "来源原始标签/数值、标准化数值、截至日、期间、定义与可比性说明均为必填。"; return; }
      if (metric.requiresCurrency && !form.value.currency.trim()) { error.value = "该金额指标必须记录原披露币种。"; return; }
      if (metric.requiresAmountScale && !form.value.amountScale.trim()) { error.value = "该金额指标必须记录原披露缩放单位。"; return; }
      saving.value = true; error.value = ""; notice.value = "";
      try { const response = await fetch(endpoint(), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ financialProfileId, evidenceReferenceId: evidence.reusableEvidenceReference.evidenceReferenceId, metricKey: metric.metricKey, reportedLabel: form.value.reportedLabel.trim(), reportedValue: form.value.reportedValue.trim(), valueNumber, unit: metric.normalizedUnit, currency: metric.requiresCurrency ? form.value.currency.trim() : null, amountScale: metric.requiresAmountScale ? form.value.amountScale.trim() : null, asOf: form.value.asOf, periodLabel: form.value.periodLabel.trim(), definitionNote: form.value.definitionNote.trim(), comparabilityNote: form.value.comparabilityNote.trim(), recordedBy: "local-user" }) }); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "保存金融专属来源事实失败"); form.value = empty(); await refresh(); notice.value = "已追加来源事实；不会自动写入模型、预测、估值或投资决策。"; }
      catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); }
      finally { saving.value = false; }
    };
    onMounted(() => { void load(); });
    const field = (label: string, key: keyof Form, wide = false, type = "text") => h("label", { class: wide ? "wide" : "" }, [label, type === "textarea" ? h("textarea", { value: form.value[key], onInput: (event: Event) => form.value = { ...form.value, [key]: (event.target as HTMLTextAreaElement).value } }) : h("input", { type, value: form.value[key], onInput: (event: Event) => form.value = { ...form.value, [key]: (event.target as HTMLInputElement).value } })]);
    const source = (fact: Fact) => { const url = fact.sourceUrl || fact.contentUrl; return url ? h("a", { href: url, target: "_blank", rel: "noreferrer" }, fact.sourceTitle || fact.sourceName || url) : h("span", "原始文档定位见证据链"); };
    return () => h("section", { class: "research-card financial-specialty-metrics" }, [
      h("style", css), h("div", { class: "section-head" }, [h("div", [h("h2", "金融机构专属指标来源账本"), h("p", { class: "research-meta mb-0" }, "按已确认的银行、保险或券商实体类型展示。没有直接来源时明确列为待补；不使用 FCF、营运资本、现金转换或 ROIC 替代。")]), h("span", { class: "research-state" }, statusLabel[ledger.value.status] || ledger.value.status)]),
      h("div", { class: "research-note mt-3" }, ledger.value.reason),
      error.value ? h("div", { class: "alert alert-warning py-2 mt-3 mb-0" }, [error.value, h("button", { class: "btn btn-link btn-sm py-0 ms-2", onClick: () => void load() }, "重试")]) : null,
      notice.value ? h("div", { class: "alert alert-success py-2 mt-3 mb-0" }, notice.value) : null,
      loading.value ? h("p", { class: "research-meta mt-3 mb-0" }, "正在读取金融专属来源事实…") : null,
      ...ledger.value.metrics.map((metric) => h("article", { class: "specialty-item", key: metric.metricKey }, [h("div", { class: "d-flex justify-content-between gap-2" }, [h("strong", metric.label), h("span", { class: "research-state" }, metric.state === "reported" ? "已披露来源" : metric.state === "conflicting" ? "冲突待澄清" : "待补来源")]), metric.fact ? h("div", { class: "mt-2 small" }, [h("div", `${metric.fact.reportedLabel}：${metric.fact.reportedValue}（标准化 ${metric.fact.valueNumber}${metric.fact.unit}${metric.fact.currency ? `，${metric.fact.currency}` : ""}${metric.fact.amountScale ? `，${metric.fact.amountScale}` : ""}）`), h("div", { class: "research-meta" }, `${metric.fact.periodLabel} · 截至 ${metric.fact.asOf}`), h("div", { class: "research-meta" }, `定义：${metric.fact.definitionNote}`), h("div", { class: "research-meta" }, `可比性：${metric.fact.comparabilityNote}`), h("div", { class: "fact-chain" }, [`evidence=${metric.fact.evidenceReferenceId} · profile=${metric.fact.financialProfileId} · ${metric.fact.sourceLocator}`]), source(metric.fact)]) : h("p", { class: "research-meta mb-0 mt-2" }, metric.reason)])),
      props.canWrite && ledger.value.status !== "blocked_entity_profile" && ledger.value.status !== "not_applicable" && ledger.value.status !== "storage_unavailable" ? h("details", { class: "mt-3", "data-research-workbench": "financial-specialty-metrics" }, [h("summary", "本地工作台：追加不可变专属来源事实"), h("div", { class: "specialty-form" }, [
        h("label", { class: "wide" }, ["专属指标", h("select", { value: form.value.metricKey, onChange: (event: Event) => chooseMetric((event.target as HTMLSelectElement).value) }, [h("option", { value: "" }, "选择当前实体类型的指标"), ...ledger.value.metrics.map((item) => h("option", { value: item.metricKey }, `${item.label} · ${item.normalizedUnit}`))])]),
        h("label", { class: "wide" }, ["已接受的信息预处理证据", h("select", { value: form.value.evidenceReferenceId, onChange: (event: Event) => form.value = { ...form.value, evidenceReferenceId: (event.target as HTMLSelectElement).value } }, [h("option", { value: "" }, "选择已接受来源；不支持手填 URL"), ...eligible().map((item) => h("option", { value: item.reusableEvidenceReference!.evidenceReferenceId }, `${item.period || "未注明期间"} · ${item.statement.slice(0, 72)}`))])]),
        field("来源原始标签", "reportedLabel"), field("来源原始数值", "reportedValue"), field("人工确认的标准化数值", "valueNumber", false, "number"), field("截至日", "asOf", false, "date"), field("报告期间", "periodLabel"), selectedMetric()?.requiresCurrency ? field("原披露币种", "currency") : null, selectedMetric()?.requiresAmountScale ? field("原披露缩放单位（如 百万元）", "amountScale") : null, field("定义、范围与监管/会计口径", "definitionNote", true, "textarea"), field("可比性及未解决口径", "comparabilityNote", true, "textarea"), h("div", { class: "wide" }, h("button", { class: "btn btn-success btn-sm", disabled: saving.value || !selectedMetric() || !profileId(), onClick: () => void save() }, saving.value ? "保存中…" : "追加不可变专属来源事实")),
      ])]) : null,
    ]);
  },
});
