import { defineComponent, h, ref } from "vue";

/** The editor intentionally keeps one source binding for a submitted version.
 * That reference is copied to every fact/assumption record in the payload, so
 * rows cannot accidentally become un-auditable while remaining practical to enter. */
type Mode = "model" | "drivers" | "market";
type Source = { url: string; title: string };
type Contract = { contractType: string; customerOrChannel: string; commitmentDescription: string; pricingBasis: string; delivery: string };
type Unit = { unitName: string; price: string; cost: string; currency: string; scale: string; period: string; contribution: string };
type Segment = { name: string; product: string; customer: string; geography: string; formula: string; revenueRecognition: string; contracts: Contract[]; units: Unit[] };
type Constraint = { segmentIndex: string; kind: string; description: string; statement: string; driver: string; release: string };
type ModelForm = { source: Source; version: string; modelType: string; primary: string; recognition: string; summary: string; segments: Segment[]; constraints: Constraint[] };
type DriverSegment = { operatingSegmentId: string; volume: string; price: string; gross: string; opex: string; da: string; capex: string; nwc: string };
type DriverYear = { fiscalYear: string; tax: string; debt: string; segments: DriverSegment[] };
type DriverForm = { source: Source; version: string; modelId: string; scenario: string; currency: string; scale: string; openingRevenue: string; openingNwc: string; years: DriverYear[] };
type Estimate = { layer: string; method: string; methodBasis: string; amount: string; currency: string; scale: string; period: string; periodKind: string; description: string; status: string };
type BridgeStep = { kind: string; direction: string; delta: string; description: string };
type Bridge = { shareType: string; period: string; start: string; end: string; unit: string; status: string; steps: BridgeStep[] };
type Pool = { period: string; revenue: string; margin: string; currency: string; scale: string; note: string; status: string };
type MarketForm = { source: Source; version: string; modelId: string; definition: string; product: string; geography: string; customer: string; measurement: string; estimates: Estimate[]; bridges: Bridge[]; pools: Pool[] };

const styles = `.operating-workbench{margin-top:1rem}.operating-tabs,.editor-actions{display:flex;gap:.45rem;flex-wrap:wrap}.operating-tabs button,.editor-actions button{border:1px solid #9bc4bd;background:#fff;border-radius:.5rem;padding:.32rem .68rem;color:#18574e;font-size:.8rem}.operating-tabs button.active{background:#0f766e;border-color:#0f766e;color:#fff}.editor-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.6rem}.editor-grid label{display:block;font-size:.76rem;color:#365653}.editor-grid input,.editor-grid select,.editor-grid textarea{display:block;width:100%;margin-top:.2rem;border:1px solid #c6d5d2;border-radius:.4rem;padding:.42rem;background:#fff}.editor-grid textarea{min-height:4.2rem}.editor-grid .wide{grid-column:1/-1}.editor-card{border:1px solid #c9ddd9;border-radius:.7rem;padding:.8rem;background:#fcfffe}.editor-card h4{font-size:.92rem;margin:0}.editor-card-header{display:flex;justify-content:space-between;gap:.5rem;align-items:center;margin-bottom:.65rem}.editor-repeat{border-top:1px dashed #c9ddd9;margin-top:.75rem;padding-top:.75rem}.editor-danger{color:#9f1239!important;border-color:#f4b6c2!important}.operating-note{border-left:4px solid #0f766e;background:#f7fffd}@media(max-width:800px){.editor-grid{grid-template-columns:1fr}}`;
const source = (): Source => ({ url: "", title: "" });
const contract = (): Contract => ({ contractType: "project", customerOrChannel: "", commitmentDescription: "", pricingBasis: "", delivery: "" });
const unit = (): Unit => ({ unitName: "", price: "", cost: "", currency: "", scale: "", period: "annual", contribution: "" });
const segment = (): Segment => ({ name: "", product: "", customer: "", geography: "", formula: "", revenueRecognition: "", contracts: [contract()], units: [unit()] });
const constraint = (): Constraint => ({ segmentIndex: "", kind: "capacity", description: "", statement: "income", driver: "", release: "" });
const model = (): ModelForm => ({ source: source(), version: "1", modelType: "product", primary: "", recognition: "", summary: "", segments: [segment()], constraints: [] });
const driverSegment = (): DriverSegment => ({ operatingSegmentId: "", volume: "", price: "", gross: "", opex: "", da: "", capex: "", nwc: "" });
const driverYear = (year = new Date().getFullYear() + 1): DriverYear => ({ fiscalYear: String(year), tax: "", debt: "", segments: [driverSegment()] });
const drivers = (): DriverForm => ({ source: source(), version: "1", modelId: "", scenario: "base", currency: "CNY", scale: "亿", openingRevenue: "", openingNwc: "", years: [driverYear()] });
const estimate = (): Estimate => ({ layer: "tam", method: "top_down", methodBasis: "terminal_demand", amount: "", currency: "CNY", scale: "亿", period: `${new Date().getFullYear() + 1}FY`, periodKind: "annual_flow", description: "", status: "available" });
const step = (): BridgeStep => ({ kind: "other", direction: "gain", delta: "", description: "" });
const bridge = (): Bridge => ({ shareType: "revenue", period: `${new Date().getFullYear() + 1}FY`, start: "", end: "", unit: "ratio", status: "draft", steps: [step()] });
const pool = (): Pool => ({ period: `${new Date().getFullYear() + 1}FY`, revenue: "", margin: "", currency: "CNY", scale: "亿", note: "", status: "draft" });
const market = (): MarketForm => ({ source: source(), version: "1", modelId: "", definition: "", product: "", geography: "", customer: "", measurement: "", estimates: [estimate(), estimate()], bridges: [], pools: [] });

export const OperatingMarketWorkbench = defineComponent({
  name: "OperatingMarketWorkbench",
  props: { securityCode: { type: String, required: true }, canWrite: { type: Boolean, default: false } },
  setup(props) {
    const mode = ref<Mode>("model"); const modelForm = ref(model()); const driverForm = ref(drivers()); const marketForm = ref(market());
    const saving = ref(false); const error = ref(""); const saved = ref("");
    const replace = <T extends object>(target: { value: T }, patch: Partial<T>) => { target.value = { ...target.value, ...patch }; };
    const resetMessage = () => { error.value = ""; saved.value = ""; };
    const save = async () => {
      saving.value = true; resetMessage();
      try {
        const now = Date.now(); let path = ""; let body: Record<string, unknown>;
        if (mode.value === "model") { path = "operating-models"; body = modelPayload(props.securityCode, modelForm.value, now); }
        else if (mode.value === "drivers") { path = "operating-driver-plans"; body = driverPayload(props.securityCode, driverForm.value, now); }
        else { path = "market-space-assessments"; body = marketPayload(props.securityCode, marketForm.value, now); }
        const response = await fetch(`/api/research/company/${encodeURIComponent(props.securityCode)}/${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
        const result = await response.json(); if (!response.ok || result.code !== 200) throw new Error(result.msg || "保存失败");
        saved.value = mode.value === "model" ? `已保存经营模型。后续驱动计划请引用模型 ID：${body.operatingModelId}` : mode.value === "drivers" ? "已保存多年度分部驱动计划；它是研究者自建分析假设，未自动形成投资结论。" : "已保存市场空间版本；上下测算、份额桥和利润池仍保持原始可审计记录，不会自动平均。";
      } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); }
      finally { saving.value = false; }
    };
    return () => h("section", { class: "research-card operating-workbench operating-note" }, [
      h("style", styles), h("div", { class: "section-head" }, [h("div", [h("h2", "经营模型、驱动树与市场空间工作台"), h("p", { class: "research-meta mb-0" }, "每次提交都是版本化公共研究记录。每一行均绑定下方证据；经营事实、分析假设与市场估算不混写。")]), h("span", { class: "research-state" }, "P3 字段化")]),
      h("div", { class: "operating-tabs mt-3" }, (["model", "drivers", "market"] as Mode[]).map((key) => h("button", { class: mode.value === key ? "active" : "", onClick: () => { mode.value = key; resetMessage(); } }, ({ model: "经营模型", drivers: "分部驱动计划", market: "市场空间" } as Record<Mode, string>)[key]))),
      mode.value === "model" ? renderModel(modelForm.value, (patch) => replace(modelForm, patch)) : null,
      mode.value === "drivers" ? renderDrivers(driverForm.value, (patch) => replace(driverForm, patch)) : null,
      mode.value === "market" ? renderMarket(marketForm.value, (patch) => replace(marketForm, patch)) : null,
      props.canWrite ? h("button", { class: "btn btn-success mt-3", disabled: saving.value, onClick: () => void save() }, saving.value ? "保存中…" : `保存${({ model: "经营模型", drivers: "驱动计划", market: "市场空间" } as Record<Mode, string>)[mode.value]}版本`) : h("div", { class: "research-note mt-3" }, "生产环境只读；研究写入仅在本地运行时开放。"),
      error.value ? h("div", { class: "alert alert-danger py-2 mt-3 mb-0" }, error.value) : null, saved.value ? h("div", { class: "alert alert-success py-2 mt-3 mb-0" }, saved.value) : null,
    ]);
  },
});

function renderModel(f: ModelForm, update: (patch: Partial<ModelForm>) => void) {
  const updateSegment = (index: number, patch: Partial<Segment>) => update({ segments: f.segments.map((item, i) => i === index ? { ...item, ...patch } : item) });
  return h("div", { class: "mt-3" }, [sourceFields(f.source, (patch) => update({ source: { ...f.source, ...patch } })), h("div", { class: "editor-grid mt-2" }, [select("模型类型", f.modelType, ["product", "project", "subscription", "platform", "resource", "financial", "mixed", "other"], (value) => update({ modelType: value })), input("版本", f.version, (value) => update({ version: value }), "number"), input("主要盈利驱动", f.primary, (value) => update({ primary: value })), input("收入确认", f.recognition, (value) => update({ recognition: value })), textarea("商业模式说明", f.summary, (value) => update({ summary: value }), true)]),
    sectionList("经营分部", "新增分部", f.segments, (item, index) => h("article", { class: "editor-card" }, [cardHeader(`分部 ${index + 1}`, f.segments.length > 1, () => update({ segments: f.segments.filter((_, i) => i !== index) })), h("div", { class: "editor-grid" }, [input("分部名称", item.name, (v) => updateSegment(index, { name: v })), input("产品范围", item.product, (v) => updateSegment(index, { product: v })), input("客户范围", item.customer, (v) => updateSegment(index, { customer: v })), input("地区范围", item.geography, (v) => updateSegment(index, { geography: v })), input("分部收入确认", item.revenueRecognition, (v) => updateSegment(index, { revenueRecognition: v })), textarea("收入公式", item.formula, (v) => updateSegment(index, { formula: v }), true)]),
      nestedList("合同/承诺", "新增合同", item.contracts, (contractItem, contractIndex) => h("div", { class: "editor-repeat" }, [cardHeader(`合同 ${contractIndex + 1}`, item.contracts.length > 1, () => updateSegment(index, { contracts: item.contracts.filter((_, i) => i !== contractIndex) })), h("div", { class: "editor-grid" }, [select("合同类型", contractItem.contractType, ["subscription", "usage", "project", "framework", "spot", "regulated_tariff", "other"], (v) => updateContract(item, contractIndex, { contractType: v }, index, updateSegment)), input("客户或渠道", contractItem.customerOrChannel, (v) => updateContract(item, contractIndex, { customerOrChannel: v }, index, updateSegment)), input("合同/承诺说明", contractItem.commitmentDescription, (v) => updateContract(item, contractIndex, { commitmentDescription: v }, index, updateSegment)), input("定价基础", contractItem.pricingBasis, (v) => updateContract(item, contractIndex, { pricingBasis: v }, index, updateSegment)), input("续约或交付约束", contractItem.delivery, (v) => updateContract(item, contractIndex, { delivery: v }, index, updateSegment))])]), () => updateSegment(index, { contracts: [...item.contracts, contract()] })),
      nestedList("单位经济", "新增单位经济", item.units, (unitItem, unitIndex) => h("div", { class: "editor-repeat" }, [cardHeader(`单位经济 ${unitIndex + 1}`, item.units.length > 1, () => updateSegment(index, { units: item.units.filter((_, i) => i !== unitIndex) })), h("div", { class: "editor-grid" }, [input("单位名称", unitItem.unitName, (v) => updateUnit(item, unitIndex, { unitName: v }, index, updateSegment)), input("单位价格", unitItem.price, (v) => updateUnit(item, unitIndex, { price: v }, index, updateSegment), "number"), input("单位变动成本", unitItem.cost, (v) => updateUnit(item, unitIndex, { cost: v }, index, updateSegment), "number"), input("币种", unitItem.currency, (v) => updateUnit(item, unitIndex, { currency: v }, index, updateSegment)), input("数值单位", unitItem.scale, (v) => updateUnit(item, unitIndex, { scale: v }, index, updateSegment)), input("期间", unitItem.period, (v) => updateUnit(item, unitIndex, { period: v }, index, updateSegment)), textarea("单位经济贡献说明", unitItem.contribution, (v) => updateUnit(item, unitIndex, { contribution: v }, index, updateSegment), true)]) ]), () => updateSegment(index, { units: [...item.units, unit()] }))]), () => update({ segments: [...f.segments, segment()] })),
    sectionList("增长约束（可选）", "新增增长约束", f.constraints, (item, index) => h("article", { class: "editor-card" }, [cardHeader(`约束 ${index + 1}`, true, () => update({ constraints: f.constraints.filter((_, i) => i !== index) })), h("div", { class: "editor-grid" }, [select("关联分部", item.segmentIndex, ["", ...f.segments.map((_, i) => String(i))], (v) => update({ constraints: f.constraints.map((x, i) => i === index ? { ...x, segmentIndex: v } : x) })), select("约束类型", item.kind, ["capacity", "customer_concentration", "certification", "regulation", "working_capital", "technology", "competition", "supply_chain", "capital", "other"], (v) => update({ constraints: f.constraints.map((x, i) => i === index ? { ...x, kind: v } : x) })), select("受影响报表", item.statement, ["income", "balance", "cashflow", "multiple"], (v) => update({ constraints: f.constraints.map((x, i) => i === index ? { ...x, statement: v } : x) })), textarea("约束说明", item.description, (v) => update({ constraints: f.constraints.map((x, i) => i === index ? { ...x, description: v } : x) }), true), input("受影响驱动", item.driver, (v) => update({ constraints: f.constraints.map((x, i) => i === index ? { ...x, driver: v } : x) })), input("解除或证伪条件", item.release, (v) => update({ constraints: f.constraints.map((x, i) => i === index ? { ...x, release: v } : x) }))])]), () => update({ constraints: [...f.constraints, constraint()] })),
  ]);
}

function renderDrivers(f: DriverForm, update: (patch: Partial<DriverForm>) => void) {
  const updateYear = (index: number, patch: Partial<DriverYear>) => update({ years: f.years.map((item, i) => i === index ? { ...item, ...patch } : item) });
  return h("div", { class: "mt-3" }, [sourceFields(f.source, (patch) => update({ source: { ...f.source, ...patch } })), h("div", { class: "editor-grid mt-2" }, [input("经营模型 ID", f.modelId, (v) => update({ modelId: v }), "text", true), select("情景", f.scenario, ["downside", "base", "upside"], (v) => update({ scenario: v })), input("版本", f.version, (v) => update({ version: v }), "number"), input("估值币种", f.currency, (v) => update({ currency: v })), input("数值单位", f.scale, (v) => update({ scale: v })), input("起始收入", f.openingRevenue, (v) => update({ openingRevenue: v }), "number"), input("起始净营运资本", f.openingNwc, (v) => update({ openingNwc: v }), "number")]), sectionList("年度驱动", "新增连续财年", f.years, (year, yearIndex) => h("article", { class: "editor-card" }, [cardHeader(`财年 ${yearIndex + 1}`, f.years.length > 1, () => update({ years: f.years.filter((_, i) => i !== yearIndex) })), h("div", { class: "editor-grid" }, [input("财年", year.fiscalYear, (v) => updateYear(yearIndex, { fiscalYear: v }), "number"), input("税率（%）", year.tax, (v) => updateYear(yearIndex, { tax: v }), "number"), input("预测净债务", year.debt, (v) => updateYear(yearIndex, { debt: v }), "number")]), nestedList("该年分部驱动", "新增分部驱动", year.segments, (segmentItem, segmentIndex) => h("div", { class: "editor-repeat" }, [cardHeader(`分部驱动 ${segmentIndex + 1}`, year.segments.length > 1, () => updateYear(yearIndex, { segments: year.segments.filter((_, i) => i !== segmentIndex) })), h("div", { class: "editor-grid" }, driverSegmentFields(segmentItem, (patch) => updateYear(yearIndex, { segments: year.segments.map((x, i) => i === segmentIndex ? { ...x, ...patch } : x) })))]), () => updateYear(yearIndex, { segments: [...year.segments, driverSegment()] }))]), () => update({ years: [...f.years, driverYear(Number(f.years.at(-1)?.fiscalYear || new Date().getFullYear()) + 1)] })), h("p", { class: "research-meta mt-2 mb-0" }, "保存前会验证年度连续性与每年分部 ID 的唯一性。行内输入只代表自建分析假设，证据仍绑定到提交版本。")]);
}

function renderMarket(f: MarketForm, update: (patch: Partial<MarketForm>) => void) {
  return h("div", { class: "mt-3" }, [sourceFields(f.source, (patch) => update({ source: { ...f.source, ...patch } })), h("div", { class: "editor-grid mt-2" }, [input("关联经营模型 ID（可选）", f.modelId, (v) => update({ modelId: v }), "text", true), textarea("市场定义", f.definition, (v) => update({ definition: v }), true), input("产品边界", f.product, (v) => update({ product: v })), input("地理边界", f.geography, (v) => update({ geography: v })), input("客户边界", f.customer, (v) => update({ customer: v })), input("计量定义", f.measurement, (v) => update({ measurement: v })), input("版本", f.version, (v) => update({ version: v }), "number")]),
    sectionList("TAM / SAM / SOM 多层估算", "新增估算", f.estimates, (item, index) => h("article", { class: "editor-card" }, [cardHeader(`估算 ${index + 1}`, f.estimates.length > 1, () => update({ estimates: f.estimates.filter((_, i) => i !== index) })), h("div", { class: "editor-grid" }, [select("层级", item.layer, ["tam", "sam", "som"], (v) => patchEstimate(f, update, index, { layer: v })), select("方法", item.method, ["top_down", "bottom_up"], (v) => patchEstimate(f, update, index, { method: v })), select("方法基础", item.methodBasis, ["terminal_demand", "unit_value", "customer_budget", "supplier_sum", "supply_capacity", "company_capacity", "customer_purchase", "other"], (v) => patchEstimate(f, update, index, { methodBasis: v })), input("金额", item.amount, (v) => patchEstimate(f, update, index, { amount: v }), "number"), input("币种", item.currency, (v) => patchEstimate(f, update, index, { currency: v })), input("数值单位", item.scale, (v) => patchEstimate(f, update, index, { scale: v })), input("期间", item.period, (v) => patchEstimate(f, update, index, { period: v })), select("期间属性", item.periodKind, ["annual_flow", "cumulative_stock", "point_in_time", "other"], (v) => patchEstimate(f, update, index, { periodKind: v })), select("可用性", item.status, ["available", "incomplete", "incomparable"], (v) => patchEstimate(f, update, index, { status: v })), textarea("计算说明", item.description, (v) => patchEstimate(f, update, index, { description: v }), true)])]), () => update({ estimates: [...f.estimates, estimate()] })),
    sectionList("市场份额桥（可选）", "新增份额桥", f.bridges, (item, index) => h("article", { class: "editor-card" }, [cardHeader(`份额桥 ${index + 1}`, true, () => update({ bridges: f.bridges.filter((_, i) => i !== index) })), h("div", { class: "editor-grid" }, [select("份额类型", item.shareType, ["revenue", "shipment", "customer_wallet", "new_market", "profit_pool", "capacity"], (v) => patchBridge(f, update, index, { shareType: v })), input("期间", item.period, (v) => patchBridge(f, update, index, { period: v })), input("起始份额（小数）", item.start, (v) => patchBridge(f, update, index, { start: v }), "number"), input("期末份额（小数）", item.end, (v) => patchBridge(f, update, index, { end: v }), "number"), select("单位", item.unit, ["ratio", "percent"], (v) => patchBridge(f, update, index, { unit: v })), select("状态", item.status, ["draft", "reviewed", "superseded"], (v) => patchBridge(f, update, index, { status: v }))]), nestedList("份额变动步骤", "新增步骤", item.steps, (stepItem, stepIndex) => h("div", { class: "editor-repeat" }, [cardHeader(`步骤 ${stepIndex + 1}`, item.steps.length > 1, () => patchBridge(f, update, index, { steps: item.steps.filter((_, i) => i !== stepIndex) })), h("div", { class: "editor-grid" }, [select("步骤类型", stepItem.kind, ["new_customer", "customer_expansion", "new_product", "customer_loss", "product_retirement", "capacity_constraint", "competition", "other"], (v) => patchStep(f, update, index, stepIndex, { kind: v })), select("方向", stepItem.direction, ["gain", "loss"], (v) => patchStep(f, update, index, stepIndex, { direction: v })), input("份额变化（小数）", stepItem.delta, (v) => patchStep(f, update, index, stepIndex, { delta: v }), "number"), textarea("原因/证据说明", stepItem.description, (v) => patchStep(f, update, index, stepIndex, { description: v }), true)])]), () => patchBridge(f, update, index, { steps: [...item.steps, step()] }))]), () => update({ bridges: [...f.bridges, bridge()] })),
    sectionList("行业利润池（可选）", "新增利润池", f.pools, (item, index) => h("article", { class: "editor-card" }, [cardHeader(`利润池 ${index + 1}`, true, () => update({ pools: f.pools.filter((_, i) => i !== index) })), h("div", { class: "editor-grid" }, [input("期间", item.period, (v) => patchPool(f, update, index, { period: v })), input("行业收入", item.revenue, (v) => patchPool(f, update, index, { revenue: v }), "number"), input("可持续经营利润率（%）", item.margin, (v) => patchPool(f, update, index, { margin: v }), "number"), input("币种", item.currency, (v) => patchPool(f, update, index, { currency: v })), input("数值单位", item.scale, (v) => patchPool(f, update, index, { scale: v })), select("状态", item.status, ["draft", "reviewed", "superseded"], (v) => patchPool(f, update, index, { status: v })), textarea("标准化/可比性说明", item.note, (v) => patchPool(f, update, index, { note: v }), true)])]), () => update({ pools: [...f.pools, pool()] })),
  ]);
}

function sourceFields(value: Source, update: (patch: Partial<Source>) => void) { return h("div", { class: "editor-grid" }, [input("来源链接（所有提交行必填）", value.url, (v) => update({ url: v }), "url"), input("来源标题（可选）", value.title, (v) => update({ title: v }))]); }
function input(label: string, value: string, onInput: (value: string) => void, type = "text", wide = false) { return h("label", { class: wide ? "wide" : "" }, [label, h("input", { type, value, onInput: (e: Event) => onInput((e.target as HTMLInputElement).value) })]); }
function textarea(label: string, value: string, onInput: (value: string) => void, wide = false) { return h("label", { class: wide ? "wide" : "" }, [label, h("textarea", { value, onInput: (e: Event) => onInput((e.target as HTMLTextAreaElement).value) })]); }
function select(label: string, value: string, options: string[], onChange: (value: string) => void) { return h("label", [label, h("select", { value, onChange: (e: Event) => onChange((e.target as HTMLSelectElement).value) }, options.map((item) => h("option", { value: item }, item || "（全公司）")))]); }
function cardHeader(title: string, canRemove: boolean, remove: () => void) { return h("div", { class: "editor-card-header" }, [h("h4", title), canRemove ? h("button", { class: "editor-danger", onClick: remove }, "删除") : h("span")]); }
function sectionList<T>(title: string, addLabel: string, items: T[], render: (item: T, index: number) => ReturnType<typeof h>, add: () => void) { return h("section", { class: "mt-3" }, [h("div", { class: "editor-card-header" }, [h("h3", { class: "h6 mb-0" }, `${title}（${items.length}）`), h("button", { onClick: add }, addLabel)]), ...items.map(render)]); }
function nestedList<T>(title: string, addLabel: string, items: T[], render: (item: T, index: number) => ReturnType<typeof h>, add: () => void) { return h("section", { class: "mt-3" }, [h("div", { class: "editor-card-header" }, [h("strong", title), h("button", { onClick: add }, addLabel)]), ...items.map(render)]); }
function updateContract(segmentItem: Segment, index: number, patch: Partial<Contract>, segmentIndex: number, update: (index: number, patch: Partial<Segment>) => void) { update(segmentIndex, { contracts: segmentItem.contracts.map((x, i) => i === index ? { ...x, ...patch } : x) }); }
function updateUnit(segmentItem: Segment, index: number, patch: Partial<Unit>, segmentIndex: number, update: (index: number, patch: Partial<Segment>) => void) { update(segmentIndex, { units: segmentItem.units.map((x, i) => i === index ? { ...x, ...patch } : x) }); }
function driverSegmentFields(item: DriverSegment, update: (patch: Partial<DriverSegment>) => void) { return [input("经营分部 ID", item.operatingSegmentId, (v) => update({ operatingSegmentId: v }), "text", true), input("销量/项目数", item.volume, (v) => update({ volume: v }), "number"), input("单价", item.price, (v) => update({ price: v }), "number"), input("毛利率（%）", item.gross, (v) => update({ gross: v }), "number"), input("运营费用率（%）", item.opex, (v) => update({ opex: v }), "number"), input("折旧摊销率（%）", item.da, (v) => update({ da: v }), "number"), input("资本开支率（%）", item.capex, (v) => update({ capex: v }), "number"), input("营运资本/收入（%）", item.nwc, (v) => update({ nwc: v }), "number")]; }
function patchEstimate(f: MarketForm, update: (patch: Partial<MarketForm>) => void, index: number, patch: Partial<Estimate>) { update({ estimates: f.estimates.map((x, i) => i === index ? { ...x, ...patch } : x) }); }
function patchBridge(f: MarketForm, update: (patch: Partial<MarketForm>) => void, index: number, patch: Partial<Bridge>) { update({ bridges: f.bridges.map((x, i) => i === index ? { ...x, ...patch } : x) }); }
function patchStep(f: MarketForm, update: (patch: Partial<MarketForm>) => void, bridgeIndex: number, index: number, patch: Partial<BridgeStep>) { const item = f.bridges[bridgeIndex]; patchBridge(f, update, bridgeIndex, { steps: item.steps.map((x, i) => i === index ? { ...x, ...patch } : x) }); }
function patchPool(f: MarketForm, update: (patch: Partial<MarketForm>) => void, index: number, patch: Partial<Pool>) { update({ pools: f.pools.map((x, i) => i === index ? { ...x, ...patch } : x) }); }
function sourceRefs(value: Source) { const url = required(value.url, "来源链接"); return [{ sourceKind: "external_url", url, title: value.title.trim() || url, publishedAt: Date.now() }]; }
function modelPayload(code: string, f: ModelForm, now: number) { const refs = sourceRefs(f.source); const id = `operating-model:${code}:${now}`; return { operatingModelId: id, asOf: now, version: integer(f.version, "版本"), status: "draft", modelType: f.modelType, primaryEarningDriver: required(f.primary, "主要盈利驱动"), revenueRecognition: required(f.recognition, "收入确认"), summary: required(f.summary, "商业模式说明"), epistemicType: "observed_fact", sourceReferences: refs, segments: f.segments.map((item, index) => { const segmentId = `${id}:segment:${index + 1}`; return { operatingSegmentId: segmentId, name: required(item.name, "分部名称"), productScope: required(item.product, "产品范围"), customerScope: required(item.customer, "客户范围"), geographicScope: required(item.geography, "地区范围"), revenueFormula: required(item.formula, "分部收入公式"), revenueRecognition: required(item.revenueRecognition, "分部收入确认"), sortOrder: index + 1, sourceReferences: refs, contracts: item.contracts.map((x, i) => ({ contractDriverId: `${segmentId}:contract:${i + 1}`, contractType: x.contractType, customerOrChannel: required(x.customerOrChannel, "客户或渠道"), commitmentDescription: required(x.commitmentDescription, "合同/承诺说明"), pricingBasis: required(x.pricingBasis, "定价基础"), renewalOrDeliveryConstraint: required(x.delivery, "续约或交付约束"), startPeriod: null, endPeriod: null, sortOrder: i + 1, sourceReferences: refs })), unitEconomics: item.units.map((x, i) => ({ unitEconomicId: `${segmentId}:unit:${i + 1}`, unitName: required(x.unitName, "单位名称"), pricePerUnit: finiteOrNull(x.price, "单位价格"), variableCostPerUnit: finiteOrNull(x.cost, "单位变动成本"), currency: x.price.trim() || x.cost.trim() ? required(x.currency, "单位经济币种") : null, amountScale: x.price.trim() || x.cost.trim() ? required(x.scale, "单位经济数值单位") : null, periodBasis: required(x.period, "单位经济期间"), contributionDescription: required(x.contribution, "单位经济贡献说明"), sortOrder: i + 1, sourceReferences: refs })) }; }), growthConstraints: f.constraints.map((x, i) => ({ growthConstraintId: `${id}:constraint:${i + 1}`, operatingSegmentId: x.segmentIndex === "" ? null : `${id}:segment:${integer(x.segmentIndex, "关联分部") + 1}`, constraintKind: x.kind, description: required(x.description, "增长约束说明"), affectedStatement: x.statement, affectedDriver: required(x.driver, "受影响驱动"), invalidationOrReleaseCondition: required(x.release, "解除或证伪条件"), sortOrder: i + 1, sourceReferences: refs })), createdAt: now, updatedAt: now }; }
function driverPayload(code: string, f: DriverForm, now: number) { const refs = sourceRefs(f.source); const id = `operating-driver-plan:${code}:${now}`; return { operatingDriverPlanId: id, operatingModelId: required(f.modelId, "经营模型 ID"), scenarioName: f.scenario, asOf: now, version: integer(f.version, "版本"), status: "draft", valuationCurrency: required(f.currency, "估值币种"), amountScale: required(f.scale, "数值单位"), openingRevenue: positive(f.openingRevenue, "起始收入"), openingNetWorkingCapital: finite(f.openingNwc, "起始净营运资本"), epistemicType: "analysis_assumption", sourceReferences: refs, years: f.years.map((year, yearIndex) => ({ operatingDriverPlanYearId: `${id}:year:${yearIndex + 1}`, fiscalYear: integer(year.fiscalYear, "财年"), taxRate: rate(year.tax, "税率"), forecastNetDebt: finite(year.debt, "预测净债务"), sortOrder: yearIndex + 1, sourceReferences: refs, segments: year.segments.map((x, i) => ({ operatingDriverSegmentYearId: `${id}:year:${yearIndex + 1}:segment:${i + 1}`, operatingSegmentId: required(x.operatingSegmentId, "经营分部 ID"), volume: nonnegative(x.volume, "销量/项目数"), pricePerUnit: finite(x.price, "单价"), grossMargin: rate(x.gross, "毛利率"), operatingExpenseMargin: rate(x.opex, "运营费用率"), depreciationAmortizationMargin: rate(x.da, "折旧摊销率"), capitalExpenditureMargin: rate(x.capex, "资本开支率"), netWorkingCapitalToRevenue: rate(x.nwc, "营运资本/收入"), sortOrder: i + 1, sourceReferences: refs })) })), createdAt: now, updatedAt: now }; }
function marketPayload(code: string, f: MarketForm, now: number) { const refs = sourceRefs(f.source); const id = `market-space:${code}:${now}`; return { marketSpaceAssessmentId: id, operatingModelId: f.modelId.trim() || null, asOf: now, version: integer(f.version, "版本"), status: "draft", marketDefinition: required(f.definition, "市场定义"), productBoundary: required(f.product, "产品边界"), geographicBoundary: required(f.geography, "地理边界"), customerBoundary: required(f.customer, "客户边界"), measurementDefinition: required(f.measurement, "计量定义"), epistemicType: "observed_fact", sourceReferences: refs, estimates: f.estimates.map((x, i) => ({ marketSpaceEstimateId: `${id}:estimate:${i + 1}`, layer: x.layer, method: x.method, methodBasis: x.methodBasis, amount: nonnegative(x.amount, "市场估算金额"), currency: required(x.currency, "市场币种"), amountScale: required(x.scale, "市场数值单位"), periodLabel: required(x.period, "市场期间"), periodKind: x.periodKind, calculationDescription: required(x.description, "计算说明"), status: x.status, sortOrder: i + 1, sourceReferences: refs })), shareBridges: f.bridges.map((x, i) => { const bridgeId = `${id}:bridge:${i + 1}`; return { marketShareBridgeId: bridgeId, shareType: x.shareType, periodLabel: required(x.period, "份额桥期间"), startingShare: shareValue(x.start, x.unit, "起始份额"), endingShare: shareValue(x.end, x.unit, "期末份额"), unit: x.unit, status: x.status, sourceReferences: refs, steps: x.steps.map((stepItem, stepIndex) => ({ marketShareBridgeStepId: `${bridgeId}:step:${stepIndex + 1}`, stepKind: stepItem.kind, direction: stepItem.direction, shareDelta: nonnegative(stepItem.delta, "份额变化"), description: required(stepItem.description, "份额变动原因"), sortOrder: stepIndex + 1, sourceReferences: refs })), createdAt: now, updatedAt: now }; }), profitPools: f.pools.map((x, i) => ({ marketProfitPoolId: `${id}:pool:${i + 1}`, periodLabel: required(x.period, "利润池期间"), industryRevenue: nonnegative(x.revenue, "行业收入"), sustainableOperatingMargin: rate(x.margin, "可持续经营利润率"), currency: required(x.currency, "利润池币种"), amountScale: required(x.scale, "利润池数值单位"), normalizationNote: required(x.note, "标准化/可比性说明"), status: x.status, sourceReferences: refs, createdAt: now, updatedAt: now })), createdAt: now, updatedAt: now }; }
function required(value: string, label: string) { const result = value.trim(); if (!result) throw new Error(`${label}不能为空`); return result; }
function finite(value: string, label: string) { const result = Number(value); if (!Number.isFinite(result)) throw new Error(`${label}必须为有限数值`); return result; }
function finiteOrNull(value: string, label: string) { return value.trim() ? finite(value, label) : null; }
function integer(value: string, label: string) { const result = finite(value, label); if (!Number.isInteger(result) || result < 0) throw new Error(`${label}必须为非负整数`); return result; }
function positive(value: string, label: string) { const result = finite(value, label); if (result <= 0) throw new Error(`${label}必须大于零`); return result; }
function nonnegative(value: string, label: string) { const result = finite(value, label); if (result < 0) throw new Error(`${label}必须不小于零`); return result; }
function rate(value: string, label: string) { return finite(value, label) / 100; }
function shareValue(value: string, unit: string, label: string) { const result = nonnegative(value, label); if ((unit === "ratio" && result > 1) || (unit === "percent" && result > 100)) throw new Error(`${label}超出单位范围`); return result; }
