import { defineComponent, h, onMounted, ref } from "vue";

type Fact = { operatingSourceFactId: string; factKind: string; subjectLabel: string; periodLabel: string; reportedValue: string; sourceSecurityCode: string };
type TargetField = { field: string; factKinds: string[] };
type TargetSchema = { targetKind: TargetKind; targetFields: TargetField[] };
type TargetKind = "segment_variable" | "contract_parameter" | "growth_constraint";
type Model = { operatingModelId: string; version: number; status: string; segments: Array<{ operatingSegmentId: string; name: string; contracts: Array<{ contractDriverId: string; customerOrChannel: string }> }>; growthConstraints: Array<{ growthConstraintId: string; description: string }> };
type Binding = { operatingSourceFactBindingId: string; operatingSourceFactId: string; operatingModelId: string; targetKind: TargetKind; targetId: string; targetField: string; factKind: string; formula: string; applicablePeriod: string; applicabilityDescription: string; uncoveredScope: string; reviewStatus: string; reviewNote: string | null; reviewedBy: string | null; reviewedAt: number | null; createdBy: string; createdAt: number };
type Body = { code?: number; msg?: string; data?: { bindings?: { availability?: string; reason?: string | null; items?: Binding[]; reviewedInputs?: Binding[] }; sourceFacts?: { items?: Fact[] }; operatingModels?: { items?: Model[] }; targetSchema?: TargetSchema[] } };
type Form = { factId: string; modelId: string; targetKind: TargetKind; targetId: string; targetField: string; formula: string; applicablePeriod: string; applicabilityDescription: string; uncoveredScope: string };
const labels: Record<TargetKind, string> = { segment_variable: "分部变量", contract_parameter: "合同参数", growth_constraint: "增长约束" };
const empty = (): Form => ({ factId: "", modelId: "", targetKind: "segment_variable", targetId: "", targetField: "", formula: "", applicablePeriod: "", applicabilityDescription: "", uncoveredScope: "" });
const css = `.operating-source-fact-bindings{border-left:4px solid #7c3aed}.operating-source-fact-bindings .binding-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.55rem;padding:.7rem;margin-top:.7rem;border-radius:.6rem;background:#f5f3ff}.operating-source-fact-bindings label{font-size:.79rem;color:#3b246b}.operating-source-fact-bindings input,.operating-source-fact-bindings select,.operating-source-fact-bindings textarea{width:100%;margin-top:.2rem;border:1px solid #c4b5fd;border-radius:.4rem;padding:.4rem;background:#fff}.operating-source-fact-bindings textarea{min-height:3.5rem}.operating-source-fact-bindings .wide{grid-column:1/-1}.operating-source-fact-bindings .binding-item{border-top:1px solid #ddd6fe;padding:.8rem 0}.operating-source-fact-bindings .binding-item:first-of-type{border-top:0}.operating-source-fact-bindings .binding-chain{font:normal .72rem ui-monospace,SFMono-Regular,Menlo,monospace;color:#5b6076;overflow-wrap:anywhere}.operating-source-fact-bindings .review-box{margin-top:.55rem;padding:.55rem;border-radius:.5rem;background:#faf5ff}@media(max-width:600px){.operating-source-fact-bindings .binding-form{grid-template-columns:1fr}}`;
function date(value: number | null) { return value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : "未复核"; }

/**
 * Makes a source-to-model interpretation visible, reviewable and bounded. It
 * intentionally has no "apply" action: reviewed inputs still require a human
 * to author a later immutable operating-model or driver-plan version.
 */
export const OperatingSourceFactBindingsPanel = defineComponent({
  name: "OperatingSourceFactBindingsPanel",
  props: { securityCode: { type: String, required: true }, canWrite: { type: Boolean, required: true }, initial: { type: Object, required: false, default: null } },
  setup(props) {
    const bindings = ref<Binding[]>(Array.isArray((props.initial as any)?.items) ? (props.initial as any).items : []);
    const facts = ref<Fact[]>([]); const models = ref<Model[]>([]); const schema = ref<TargetSchema[]>([]); const loading = ref(true); const saving = ref(false); const error = ref(""); const form = ref<Form>(empty());
    const reviewBindingId = ref(""); const reviewStatus = ref("reviewed"); const reviewNote = ref("");
    const endpoint = () => `/api/research/company/${encodeURIComponent(props.securityCode)}/operating-source-fact-bindings`;
    const selectedFact = () => facts.value.find((item) => item.operatingSourceFactId === form.value.factId) || null;
    const selectedModel = () => models.value.find((item) => item.operatingModelId === form.value.modelId) || null;
    const targetFieldSchema = () => schema.value.find((item) => item.targetKind === form.value.targetKind)?.targetFields || [];
    const compatibleFields = () => targetFieldSchema().filter((item) => !selectedFact() || item.factKinds.includes(selectedFact()!.factKind));
    const targets = () => { const model = selectedModel(); if (!model) return [] as Array<{ id: string; label: string }>; if (form.value.targetKind === "segment_variable") return model.segments.map((item) => ({ id: item.operatingSegmentId, label: item.name })); if (form.value.targetKind === "contract_parameter") return model.segments.flatMap((segment) => segment.contracts.map((item) => ({ id: item.contractDriverId, label: `${segment.name} · ${item.customerOrChannel}` }))); return model.growthConstraints.map((item) => ({ id: item.growthConstraintId, label: item.description })); };
    const resetTarget = () => { form.value = { ...form.value, targetId: "", targetField: "" }; };
    const load = async () => { loading.value = true; error.value = ""; try { const response = await fetch(endpoint()); const body = await response.json() as Body; if (!response.ok || body.code !== 200) throw new Error(body.msg || "读取来源事实绑定失败"); bindings.value = body.data?.bindings?.items || []; facts.value = body.data?.sourceFacts?.items || []; models.value = body.data?.operatingModels?.items || []; schema.value = body.data?.targetSchema || []; } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { loading.value = false; } };
    const save = async () => { const item = form.value; if (!item.factId || !item.modelId || !item.targetId || !item.targetField || !item.formula.trim() || !item.applicablePeriod.trim() || !item.applicabilityDescription.trim() || !item.uncoveredScope.trim()) { error.value = "来源事实、模型、目标字段、公式、适用期、适用范围和未覆盖项均为必填。"; return; } saving.value = true; error.value = ""; try { const response = await fetch(endpoint(), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ operatingSourceFactId: item.factId, operatingModelId: item.modelId, targetKind: item.targetKind, targetId: item.targetId, targetField: item.targetField, formula: item.formula.trim(), applicablePeriod: item.applicablePeriod.trim(), applicabilityDescription: item.applicabilityDescription.trim(), uncoveredScope: item.uncoveredScope.trim(), createdBy: "local-user" }) }); const body = await response.json() as Body; if (!response.ok || body.code !== 200) throw new Error(body.msg || "保存来源事实绑定失败"); form.value = empty(); await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { saving.value = false; } };
    const review = async () => { if (!reviewBindingId.value || !reviewNote.value.trim()) { error.value = "请选择绑定并写明复核理由。"; return; } saving.value = true; error.value = ""; try { const response = await fetch(`${endpoint()}/${encodeURIComponent(reviewBindingId.value)}/reviews`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reviewStatus: reviewStatus.value, reviewNote: reviewNote.value.trim(), reviewedBy: "local-user" }) }); const body = await response.json() as Body; if (!response.ok || body.code !== 200) throw new Error(body.msg || "复核来源事实绑定失败"); reviewBindingId.value = ""; reviewNote.value = ""; await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { saving.value = false; } };
    const select = (label: string, value: string, set: (value: string) => void, options: Array<{ value: string; label: string }>, wide = false) => h("label", { class: wide ? "wide" : "" }, [label, h("select", { value, onChange: (e: Event) => set((e.target as HTMLSelectElement).value) }, [h("option", { value: "" }, "请选择"), ...options.map((option) => h("option", { value: option.value }, option.label))])]);
    const field = (label: string, key: keyof Form, wide = false, textarea = false) => h("label", { class: wide ? "wide" : "" }, [label, textarea ? h("textarea", { value: form.value[key], onInput: (e: Event) => form.value = { ...form.value, [key]: (e.target as HTMLTextAreaElement).value } }) : h("input", { value: form.value[key], onInput: (e: Event) => form.value = { ...form.value, [key]: (e.target as HTMLInputElement).value } })]);
    onMounted(() => { void load(); });
    return () => h("section", { class: "research-card operating-source-fact-bindings" }, [
      h("style", css), h("div", { class: "section-head" }, [h("div", [h("h2", "经营来源事实 → 模型字段绑定"), h("p", { class: "research-meta mb-0" }, "绑定只记录人工解释与复核状态。即使已复核，也只作为可供人工写入下一版模型的输入候选，不会回写收入、利润、现金流、情景或估值。")]), h("span", { class: "research-state" }, props.canWrite ? "本地复核" : "生产只读")]),
      error.value ? h("div", { class: "alert alert-warning py-2 mt-3 mb-0" }, error.value) : null,
      loading.value ? h("p", { class: "research-meta mt-3 mb-0" }, "正在读取受控模型输入…") : null,
      !loading.value && !bindings.value.length ? h("div", { class: "research-note mt-3" }, "尚无受控绑定。先建立已接受来源事实和字段化经营模型；缺少其中任一项时，不应以合同金额或主观假设代替模型输入。") : null,
      ...bindings.value.map((item) => h("article", { class: "binding-item", key: item.operatingSourceFactBindingId }, [h("div", { class: "d-flex justify-content-between gap-2" }, [h("strong", `${labels[item.targetKind]} · ${item.targetField}`), h("span", { class: "research-state" }, item.reviewStatus)]), h("p", { class: "small mb-1 mt-2" }, `公式：${item.formula}`), h("p", { class: "research-meta mb-1" }, `适用期：${item.applicablePeriod}；适用：${item.applicabilityDescription}`), h("p", { class: "research-meta mb-1" }, `未覆盖：${item.uncoveredScope}`), h("p", { class: "binding-chain mb-0" }, `binding=${item.operatingSourceFactBindingId} · fact=${item.operatingSourceFactId} (${item.factKind}) · model=${item.operatingModelId} · target=${item.targetId} · created=${date(item.createdAt)}${item.reviewedAt ? ` · reviewed=${date(item.reviewedAt)}` : ""}`), item.reviewNote ? h("p", { class: "research-meta mt-1 mb-0" }, `复核：${item.reviewNote}`) : null])),
      props.canWrite ? h("div", { class: "binding-form" }, [
        select("来源事实", form.value.factId, (value) => { form.value = { ...form.value, factId: value, targetField: "" }; }, facts.value.map((item) => ({ value: item.operatingSourceFactId, label: `${item.factKind} · ${item.periodLabel} · ${item.subjectLabel}` })), true),
        select("经营模型版本", form.value.modelId, (value) => { form.value = { ...form.value, modelId: value }; resetTarget(); }, models.value.map((item) => ({ value: item.operatingModelId, label: `v${item.version} · ${item.status} · ${item.operatingModelId}` })), true),
        select("目标类型", form.value.targetKind, (value) => { form.value = { ...form.value, targetKind: value as TargetKind }; resetTarget(); }, Object.entries(labels).map(([value, label]) => ({ value, label }))),
        select("目标对象", form.value.targetId, (value) => form.value = { ...form.value, targetId: value }, targets().map((item) => ({ value: item.id, label: item.label }))),
        select("允许字段（按来源事实类型过滤）", form.value.targetField, (value) => form.value = { ...form.value, targetField: value }, compatibleFields().map((item) => ({ value: item.field, label: item.field })), true),
        field("公式/转换规则（不执行）", "formula", true, true), field("适用期间", "applicablePeriod"), field("适用范围/口径", "applicabilityDescription", true, true), field("未覆盖范围（不可留空）", "uncoveredScope", true, true), h("div", { class: "wide" }, h("button", { class: "btn btn-primary btn-sm", disabled: saving.value, onClick: () => void save() }, saving.value ? "保存中…" : "保存待复核绑定")),
      ]) : null,
      props.canWrite && bindings.value.length ? h("div", { class: "review-box" }, [h("strong", { class: "small" }, "追加复核（不会改写原绑定）"), select("绑定", reviewBindingId.value, (value) => reviewBindingId.value = value, bindings.value.map((item) => ({ value: item.operatingSourceFactBindingId, label: `${item.reviewStatus} · ${item.targetField} · ${item.operatingSourceFactBindingId}` })), true), select("复核结果", reviewStatus.value, (value) => reviewStatus.value = value, [{ value: "reviewed", label: "已复核：释放为模型输入候选" }, { value: "needs_revision", label: "需修订" }, { value: "rejected", label: "拒绝" }], true), h("label", { class: "wide" }, ["复核说明", h("textarea", { value: reviewNote.value, onInput: (e: Event) => reviewNote.value = (e.target as HTMLTextAreaElement).value })]), h("button", { class: "btn btn-outline-primary btn-sm mt-2", disabled: saving.value, onClick: () => void review() }, "追加复核记录")]) : null,
    ]);
  },
});
