import { defineComponent, h, onMounted, ref } from "vue";
import { projectOperatingScenarioForValuation, type OperatingScenarioAnnualProjection, type SelfBuiltOperatingScenario } from "../../../../../src/modules/research/application/operating-scenario-valuation";

type YearRow = { fiscalYear: string; revenueGrowth: string; ebitMargin: string; taxRate: string; daMargin: string; capexMargin: string; nwcRatio: string; forecastDebt: string };
type FormalActualOption = { actualId: string; metric: string; fiscalPeriod: string; currency: string | null; normalizedValue: number | null; normalizedUnit: string | null; normalizationStatus: string; actualStatus: string; sourceReferences: unknown[] };
const style = `.scenario-workbench{margin-top:1rem}.scenario-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.6rem}.scenario-grid label{display:block;font-size:.76rem;color:#365653}.scenario-grid input,.scenario-grid select{width:100%;border:1px solid #c6d5d2;border-radius:.4rem;padding:.4rem;margin-top:.2rem}.scenario-year{border-top:1px solid #dbe7e5;padding:.7rem 0}.scenario-result{background:#effaf8;border:1px solid #9bcfc5;border-radius:.75rem;padding:.8rem}.scenario-result table{font-size:.8rem}@media(max-width:800px){.scenario-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.scenario-grid{grid-template-columns:1fr}}`;

export const OperatingScenarioWorkbench = defineComponent({
  name: "OperatingScenarioWorkbench",
  props: { securityCode: { type: String, required: true }, canWrite: { type: Boolean, default: false }, securityCurrency: { type: String, default: "" }, underlyingSharesPerSecurity: { type: Number, default: 1 } },
  setup(props) {
    const now = new Date(); const firstYear = now.getFullYear() + 1;
    const scenarioName = ref<"downside" | "base" | "upside">("base"); const version = ref("1"); const currency = ref(props.securityCurrency || "CNY"); const amountScale = ref("亿");
    const openingRevenue = ref(""); const openingNwc = ref(""); const wacc = ref("10"); const terminalGrowth = ref("3"); const netDebt = ref(""); const netDebtSourceUrl = ref(""); const dilutedShares = ref(""); const dilutedSharesSourceUrl = ref("");
    const fxRate = ref(""); const fxSourceUrl = ref(""); const rows = ref<YearRow[]>([year(String(firstYear)), year(String(firstYear + 1))]); const formalActuals = ref<FormalActualOption[]>([]); const formalActualAnchorId = ref(""); const formalActualLoadError = ref("");
    const preview = ref<ReturnType<typeof projectOperatingScenarioForValuation> | null>(null); const error = ref(""); const saving = ref(false); const saved = ref("");
    const update = (index: number, key: keyof YearRow, value: string) => { rows.value = rows.value.map((row, current) => current === index ? { ...row, [key]: value } : row); };
    const scenario = (): SelfBuiltOperatingScenario => ({
      scenarioId: `operating-scenario:${props.securityCode}:${scenarioName.value}:${version.value}`, scenarioName: scenarioName.value, version: whole(version.value), asOf: Date.now(), valuationCurrency: requiredCurrency(currency.value), amountScale: requiredText(amountScale.value, "数值单位"), openingRevenue: positive(openingRevenue.value, "起始收入"), openingNetWorkingCapital: finite(openingNwc.value, "起始净营运资本"),
      valuation: { wacc: percent(wacc.value), terminalGrowth: percent(terminalGrowth.value), netDebtAtValuation: finite(netDebt.value, "估值日净债务"), netDebtSourceReferences: [externalReference(netDebtSourceUrl.value, "估值日净债务来源")], dilutedShares: positive(dilutedShares.value, "稀释后股数"), dilutedSharesSourceReferences: [externalReference(dilutedSharesSourceUrl.value, "稀释后股数来源")] },
      years: rows.value.map((row) => ({ fiscalYear: whole(row.fiscalYear), revenueGrowth: percent(row.revenueGrowth), ebitMargin: percent(row.ebitMargin), taxRate: percent(row.taxRate), depreciationAmortizationMargin: percent(row.daMargin), capitalExpenditureMargin: percent(row.capexMargin), netWorkingCapitalToRevenue: percent(row.nwcRatio), forecastNetDebt: finite(row.forecastDebt, "预测净债务") })),
    });
    const calculate = () => { error.value = ""; saved.value = ""; try { preview.value = projectOperatingScenarioForValuation(scenario()); } catch (reason) { preview.value = null; error.value = reason instanceof Error ? reason.message : String(reason); } };
    const loadFormalActuals = async () => { if (!props.canWrite) return; try { const response = await fetch(`/api/research/company/${encodeURIComponent(props.securityCode)}/forecasts`); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "读取正式实际失败"); formalActuals.value = Array.isArray(body.data?.formalActuals) ? body.data.formalActuals : []; } catch (reason) { formalActualLoadError.value = reason instanceof Error ? reason.message : String(reason); } };
    const save = async () => { if (!preview.value) return; saving.value = true; error.value = ""; saved.value = ""; try { const sameCurrency = currency.value.trim().toUpperCase() === props.securityCurrency.trim().toUpperCase(); const response = await fetch(`/api/research/company/${encodeURIComponent(props.securityCode)}/valuation-models/operating-scenario`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scenario: scenario(), target: { securityCurrency: props.securityCurrency || currency.value, underlyingSharesPerSecurity: props.underlyingSharesPerSecurity || 1, fxRateToSecurity: sameCurrency ? null : finite(fxRate.value, "FX"), fxAsOf: sameCurrency ? null : Date.now(), fxSourceReferences: sameCurrency ? [] : [{ sourceKind: "external_url", url: validUrl(fxSourceUrl.value), title: "FX source" }] }, formalActualAnchorIds: formalActualAnchorId.value ? [formalActualAnchorId.value] : [] }) }); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "保存经营情景模型失败"); saved.value = `已保存情景驱动的不可变 DCF 版本：${body.data.modelVersionId}${formalActualAnchorId.value ? "；已追加正式实际锚定，不覆盖自建起始收入。" : ""}`; } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { saving.value = false; } };
    onMounted(() => { void loadFormalActuals(); });
    return () => h("section", { class: "research-card scenario-workbench" }, [h("style", style), h("div", { class: "section-head" }, [h("div", [h("h2", "自建经营情景 → 不可变估值版本"), h("p", { class: "research-meta mb-0" }, "自建假设与正式实际分层。可选的正式实际只作为来源锚定追加到模型，不会覆盖自建起始收入、情景路径或估值日净债务。")]), h("span", { class: "research-state" }, "自建假设")]),
      h("div", { class: "scenario-grid mt-3" }, [select("情景", scenarioName.value, [["downside", "悲观"], ["base", "基准"], ["upside", "乐观"]], (value) => { scenarioName.value = value as typeof scenarioName.value; }), field("版本", version.value, (value) => { version.value = value; }, "number"), field("估值币种", currency.value, (value) => { currency.value = value; }), field("数值单位", amountScale.value, (value) => { amountScale.value = value; }), field("起始收入", openingRevenue.value, (value) => { openingRevenue.value = value; }, "number"), field("起始净营运资本", openingNwc.value, (value) => { openingNwc.value = value; }, "number"), h("label", ["可选：正式披露收入锚定（服务端校验）", h("select", { value: formalActualAnchorId.value, onChange: (event: Event) => { formalActualAnchorId.value = (event.target as HTMLSelectElement).value; } }, [h("option", { value: "" }, formalActualLoadError.value ? "正式实际读取失败（仍可不带锚定保存）" : "不追加正式实际锚定"), ...formalActuals.value.map((actual) => h("option", { value: actual.actualId }, `${actual.fiscalPeriod} · ${actual.metric} · ${actual.normalizationStatus} · ${actual.currency || "币种待补"}`))])]), field("WACC（%）", wacc.value, (value) => { wacc.value = value; }, "number"), field("终值增长（%）", terminalGrowth.value, (value) => { terminalGrowth.value = value; }, "number"), field("估值日净债务", netDebt.value, (value) => { netDebt.value = value; }, "number"), field("估值日净债务法定来源", netDebtSourceUrl.value, (value) => { netDebtSourceUrl.value = value; }, "url"), field("稀释后股数", dilutedShares.value, (value) => { dilutedShares.value = value; }, "number"), field("稀释后股数法定来源", dilutedSharesSourceUrl.value, (value) => { dilutedSharesSourceUrl.value = value; }, "url"), currency.value.trim().toUpperCase() !== props.securityCurrency.trim().toUpperCase() ? field("估值币种→证券币种 FX", fxRate.value, (value) => { fxRate.value = value; }, "number") : null, currency.value.trim().toUpperCase() !== props.securityCurrency.trim().toUpperCase() ? field("FX 来源链接", fxSourceUrl.value, (value) => { fxSourceUrl.value = value; }, "url") : null]),
      h("p", { class: "research-meta mt-3 mb-1" }, "每年输入增长、利润率、D&A、资本开支、净营运资本占收入和预测净债务；系统确定性推导收入、EBIT、NOPAT 与 UFCF。"), rows.value.map((row, index) => h("div", { class: "scenario-year" }, [h("strong", `预测年度 ${index + 1}`), h("div", { class: "scenario-grid mt-2" }, [field("财年", row.fiscalYear, (value) => update(index, "fiscalYear", value), "number"), field("收入增长（%）", row.revenueGrowth, (value) => update(index, "revenueGrowth", value), "number"), field("EBIT 利润率（%）", row.ebitMargin, (value) => update(index, "ebitMargin", value), "number"), field("税率（%）", row.taxRate, (value) => update(index, "taxRate", value), "number"), field("D&A/收入（%）", row.daMargin, (value) => update(index, "daMargin", value), "number"), field("Capex/收入（%）", row.capexMargin, (value) => update(index, "capexMargin", value), "number"), field("净营运资本/收入（%）", row.nwcRatio, (value) => update(index, "nwcRatio", value), "number"), field("预测净债务", row.forecastDebt, (value) => update(index, "forecastDebt", value), "number")])])),
      h("button", { class: "btn btn-outline-secondary btn-sm", onClick: () => { const next = whole(rows.value.at(-1)?.fiscalYear || String(firstYear)) + 1; rows.value = [...rows.value, year(String(next))]; } }, "增加预测年度"), h("button", { class: "btn btn-success btn-sm ms-2", onClick: calculate }, "推导经营与现金流"), preview.value && props.canWrite ? h("button", { class: "btn btn-outline-primary btn-sm ms-2", disabled: saving.value, onClick: () => void save() }, saving.value ? "保存中…" : "保存为不可变 DCF 版本") : null, error.value ? h("div", { class: "alert alert-danger py-2 mt-3 mb-0" }, error.value) : null, saved.value ? h("div", { class: "alert alert-success py-2 mt-3 mb-0" }, saved.value) : null, preview.value ? projectionTable(preview.value.annuals, preview.value.valuationCurrency, preview.value.amountScale) : h("div", { class: "research-note mt-3" }, "尚未推导。缺失、非连续财年或 WACC 不高于终值增长时，模型拒绝输出。")]);
  },
});

function year(fiscalYear: string): YearRow { return { fiscalYear, revenueGrowth: "", ebitMargin: "", taxRate: "", daMargin: "", capexMargin: "", nwcRatio: "", forecastDebt: "" }; }
function field(label: string, value: string, update: (value: string) => void, type = "text") { return h("label", [label, h("input", { type, value, onInput: (event: Event) => update((event.target as HTMLInputElement).value) })]); }
function select(label: string, value: string, values: Array<[string, string]>, update: (value: string) => void) { return h("label", [label, h("select", { value, onChange: (event: Event) => update((event.target as HTMLSelectElement).value) }, values.map(([key, name]) => h("option", { value: key }, name)))]); }
function finite(value: string, label: string) { const result = Number(value); if (!Number.isFinite(result)) throw new Error(`${label}必须为有限数值`); return result; }
function positive(value: string, label: string) { const result = finite(value, label); if (result <= 0) throw new Error(`${label}必须大于零`); return result; }
function whole(value: string) { const result = Number(value); if (!Number.isInteger(result)) throw new Error("版本和财年必须为整数"); return result; }
function percent(value: string) { return finite(value, "百分比") / 100; }
function requiredText(value: string, label: string) { const result = value.trim(); if (!result) throw new Error(`${label}不能为空`); return result; }
function requiredCurrency(value: string) { const result = value.trim().toUpperCase(); if (!/^[A-Z]{3}$/.test(result)) throw new Error("估值币种必须为 ISO 三位代码"); return result; }
function validUrl(value: string) { const result = value.trim(); if (!/^https?:\/\//i.test(result)) throw new Error("跨币种 FX 必须填写 http(s) 来源链接"); return result; }
function externalReference(url: string, title: string) { return { sourceKind: "external_url", url: validUrl(url), title }; }
function projectionTable(rows: OperatingScenarioAnnualProjection[], currency: string, unit: string) { return h("div", { class: "scenario-result mt-3" }, [h("strong", "确定性经营情景输出（不是来源预测）"), h("div", { class: "table-responsive mt-2" }, h("table", { class: "table table-sm mb-0" }, [h("thead", h("tr", [h("th", "财年"), h("th", "收入"), h("th", "EBIT"), h("th", "NOPAT"), h("th", "UFCF"), h("th", "期末 NWC"), h("th", "预测净债务")])), h("tbody", rows.map((row) => h("tr", [h("td", row.fiscalYear), h("td", amount(row.revenue, currency, unit)), h("td", amount(row.ebit, currency, unit)), h("td", amount(row.nopat, currency, unit)), h("td", amount(row.unleveredFreeCashFlow, currency, unit)), h("td", amount(row.endingNetWorkingCapital, currency, unit)), h("td", amount(row.forecastNetDebt, currency, unit))])))]))]); }
function amount(value: number, currency: string, unit: string) { return `${value.toLocaleString("zh-CN", { maximumFractionDigits: 2 })} ${unit} ${currency}`; }
