import { defineComponent, h, ref } from "vue";

type Mode = "pressure" | "relationship" | "link" | "snapshot";
type Source = { url: string; title: string };
type Pressure = { scenarioKey: string; version: string; scope: string; title: string; transmission: string; modelVersion: string; revenueBase: string; revenueStress: string; marginBase: string; marginStress: string; resultValue: string; resultExplanation: string };
type Relationship = { scope: string; type: string; counterparty: string; description: string; transmission: string; concentration: string; concentrationBasis: string; status: string };
type Link = { riskId: string; thesisId: string; relationship: string; rationale: string };
const source = (): Source => ({ url: "", title: "" });
const pressure = (): Pressure => ({ scenarioKey: "", version: "1", scope: "operating_company", title: "", transmission: "", modelVersion: "manual-risk-model.v1", revenueBase: "", revenueStress: "", marginBase: "", marginStress: "", resultValue: "", resultExplanation: "" });
const relationship = (): Relationship => ({ scope: "operating_company", type: "customer", counterparty: "", description: "", transmission: "", concentration: "", concentrationBasis: "", status: "active" });
const link = (): Link => ({ riskId: "", thesisId: "", relationship: "pressures", rationale: "" });
const css = `.risk-workbench{margin-top:1rem;border-left:4px solid #d97706}.risk-tabs,.risk-actions{display:flex;flex-wrap:wrap;gap:.45rem}.risk-tabs button,.risk-actions button{border:1px solid #e1b77a;background:#fff;border-radius:.5rem;padding:.33rem .7rem;color:#8a4b08;font-size:.8rem}.risk-tabs button.active{background:#d97706;border-color:#d97706;color:#fff}.risk-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.65rem}.risk-grid label{font-size:.76rem;color:#6d4a25}.risk-grid input,.risk-grid select,.risk-grid textarea{display:block;width:100%;padding:.42rem;margin-top:.2rem;border:1px solid #e0c49d;border-radius:.4rem}.risk-grid textarea{min-height:4.5rem}.risk-grid .wide{grid-column:1/-1}.risk-card{border:1px solid #f0d2a8;border-radius:.7rem;padding:.8rem;background:#fffdfa;margin-top:.65rem}.risk-card-header{display:flex;justify-content:space-between;align-items:center;gap:.5rem}.risk-card-header h4{font-size:.92rem;margin:0}.risk-delete{color:#9f1239!important;border-color:#f4b6c2!important}@media(max-width:800px){.risk-grid{grid-template-columns:1fr}}`;

/** Queue entries deliberately submit one audited record per API call. The API stays
 * append-only/versioned; the UI supplies batch ergonomics without inventing a bulk
 * endpoint that could blur partial-write failures. */
export const RiskReviewWorkbench = defineComponent({
  name: "RiskReviewWorkbench",
  props: { securityCode: { type: String, required: true }, canWrite: { type: Boolean, default: false }, risks: { type: Array, default: () => [] }, theses: { type: Array, default: () => [] } },
  setup(props) {
    const mode = ref<Mode>("pressure"); const sourceForm = ref(source()); const pressures = ref<Pressure[]>([pressure()]); const relationships = ref<Relationship[]>([relationship()]); const links = ref<Link[]>([link()]);
    const completionLevel = ref("basic"); const snapshotState = ref("资料待补"); const saving = ref(false); const error = ref(""); const notice = ref(""); const stress = ref<any[]>([]);
    const set = <T extends object>(target: { value: T[] }, index: number, patch: Partial<T>) => { target.value = target.value.map((item, i) => i === index ? { ...item, ...patch } : item); };
    const clear = () => { error.value = ""; notice.value = ""; stress.value = []; };
    const post = async (path: string, body: Record<string, unknown>) => { const response = await fetch(`/api/research/company/${encodeURIComponent(props.securityCode)}/${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); if (!response.ok || json.code !== 200) throw new Error(json.msg || "保存失败"); return json.data; };
    const save = async () => { saving.value = true; clear(); try { const refs = sourceReferences(sourceForm.value); const now = Date.now();
      if (mode.value === "pressure") { const saved = await Promise.all(pressures.value.map(async (item, index) => { const id = `pressure:${props.securityCode}:${now}:${index + 1}`; await post("risk-pressure-scenarios", pressurePayload(item, id, now, refs)); const calculated = await fetch(`/api/research/company/${encodeURIComponent(props.securityCode)}/risk-pressure-scenarios/${encodeURIComponent(id)}/stress?monetaryUnit=CNYm`); const json = await calculated.json(); if (!calculated.ok || json.code !== 200) throw new Error(json.msg || "压力计算失败"); return { title: item.title, calculation: json.data }; })); stress.value = saved; notice.value = `已保存并计算 ${saved.length} 个压力情景。结果只使用明确输入，未推断缺失变量或交易结论。`; }
      else if (mode.value === "relationship") { await Promise.all(relationships.value.map((item) => post("risk-relationships", relationshipPayload(item, now, refs)))); notice.value = `已保存 ${relationships.value.length} 条关系/集中度记录；每条都是来源绑定的公共研究事实。`; }
      else if (mode.value === "link") { await Promise.all(links.value.map((item) => post("risk-thesis-links", linkPayload(item, now, refs)))); notice.value = `已建立 ${links.value.length} 条风险—命题人工复核关联；不会自动修改命题或投资决定。`; }
      else { const data = await post("public-risk-snapshots", { completionLevel: completionLevel.value, state: required(snapshotState.value, "快照状态"), asOf: now }); notice.value = `已冻结 ${data.moduleCount} 个公共模块，记录 ${data.differenceIds?.length || 0} 项字段差分。`; }
    } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { saving.value = false; } };
    return () => h("section", { class: "research-card risk-workbench" }, [h("style", css), h("div", { class: "section-head" }, [h("div", [h("h2", "风险压力、复核与公共快照工作台"), h("p", { class: "research-meta mb-0" }, "支持一次录入多项压力、关系和人工复核关联。公共研究绝不保存持仓、交易计划、owner 或个人决定。")]), h("span", { class: "research-state" }, "P6/P7 公共研究")]),
      h("div", { class: "risk-tabs mt-3" }, (["pressure", "relationship", "link", "snapshot"] as Mode[]).map((key) => h("button", { class: mode.value === key ? "active" : "", onClick: () => { mode.value = key; clear(); } }, ({ pressure: "压力情景", relationship: "集中与关系", link: "风险—命题", snapshot: "冻结快照" } as Record<Mode, string>)[key]))),
      mode.value !== "snapshot" ? renderSource(sourceForm.value, (patch) => { sourceForm.value = { ...sourceForm.value, ...patch }; }) : null,
      mode.value === "pressure" ? renderPressure(pressures.value, (index, patch) => set(pressures, index, patch), () => { pressures.value = [...pressures.value, pressure()]; }, (index) => { pressures.value = pressures.value.filter((_, i) => i !== index); }) : null,
      mode.value === "relationship" ? renderRelationships(relationships.value, (index, patch) => set(relationships, index, patch), () => { relationships.value = [...relationships.value, relationship()]; }, (index) => { relationships.value = relationships.value.filter((_, i) => i !== index); }) : null,
      mode.value === "link" ? renderLinks(links.value, props.risks as any[], props.theses as any[], (index, patch) => set(links, index, patch), () => { links.value = [...links.value, link()]; }, (index) => { links.value = links.value.filter((_, i) => i !== index); }) : null,
      mode.value === "snapshot" ? h("div", { class: "risk-grid mt-3" }, [select("覆盖层级", completionLevel.value, ["basic", "standard", "deep"], (v) => { completionLevel.value = v; }), textarea("快照状态", snapshotState.value, (v) => { snapshotState.value = v; }, true)]) : null,
      props.canWrite ? h("button", { class: "btn btn-outline-danger mt-3", disabled: saving.value, onClick: () => void save() }, saving.value ? "保存中…" : ({ pressure: `保存并计算 ${pressures.value.length} 个压力情景`, relationship: `保存 ${relationships.value.length} 条关系`, link: `建立 ${links.value.length} 条人工复核关联`, snapshot: "冻结公共快照" } as Record<Mode, string>)[mode.value]) : h("div", { class: "research-note mt-3" }, "生产环境只读。"),
      stress.value.length ? h("section", { class: "mt-3" }, stress.value.map((item) => h("div", { class: "research-note mb-2" }, [
        h("strong", `压力计算：${item.title} · ${item.calculation.availability}`),
        h("ul", { class: "research-list small mt-2 mb-0" }, item.calculation.observations.map((x: any) => h("li", `${x.label}：${x.status === "available" ? `${x.baselineValue} → ${x.stressedValue} ${x.unit || ""}` : x.limitation || "不可得"}`))),
      ]))) : null,
      error.value ? h("div", { class: "alert alert-danger py-2 mt-3 mb-0" }, error.value) : null, notice.value ? h("div", { class: "alert alert-success py-2 mt-3 mb-0" }, notice.value) : null,
    ]);
  },
});

function renderSource(value: Source, update: (patch: Partial<Source>) => void) { return h("div", { class: "risk-grid mt-3" }, [input("来源链接（本批每项必填）", value.url, (v) => update({ url: v }), "url"), input("来源标题（可选）", value.title, (v) => update({ title: v }))]); }
function renderPressure(items: Pressure[], update: (index: number, patch: Partial<Pressure>) => void, add: () => void, remove: (index: number) => void) { return renderCards("压力情景", "新增压力情景", items, add, remove, (item, index) => h("div", { class: "risk-grid" }, [input("情景键", item.scenarioKey, (v) => update(index, { scenarioKey: v })), input("版本", item.version, (v) => update(index, { version: v }), "number"), select("范围", item.scope, ["operating_company", "listed_security"], (v) => update(index, { scope: v })), input("标题", item.title, (v) => update(index, { title: v })), input("模型版本", item.modelVersion, (v) => update(index, { modelVersion: v })), textarea("传导链", item.transmission, (v) => update(index, { transmission: v }), true), input("收入基准（CNYm）", item.revenueBase, (v) => update(index, { revenueBase: v }), "number"), input("收入压力（CNYm）", item.revenueStress, (v) => update(index, { revenueStress: v }), "number"), input("EBIT 利润率基准（%）", item.marginBase, (v) => update(index, { marginBase: v }), "number"), input("EBIT 利润率压力（%）", item.marginStress, (v) => update(index, { marginStress: v }), "number"), input("研究者陈述影响（CNYm）", item.resultValue, (v) => update(index, { resultValue: v }), "number"), textarea("结果说明", item.resultExplanation, (v) => update(index, { resultExplanation: v }), true)])); }
function renderRelationships(items: Relationship[], update: (index: number, patch: Partial<Relationship>) => void, add: () => void, remove: (index: number) => void) { return renderCards("集中与关系", "新增关系", items, add, remove, (item, index) => h("div", { class: "risk-grid" }, [select("范围", item.scope, ["operating_company", "listed_security"], (v) => update(index, { scope: v })), select("关系类型", item.type, ["customer", "supplier", "geography", "product", "channel", "financing", "asset", "regulation", "other"], (v) => update(index, { type: v })), input("对手方", item.counterparty, (v) => update(index, { counterparty: v })), textarea("关系说明", item.description, (v) => update(index, { description: v }), true), textarea("风险传导", item.transmission, (v) => update(index, { transmission: v }), true), input("集中度（%）（可选）", item.concentration, (v) => update(index, { concentration: v }), "number"), input("集中度口径", item.concentrationBasis, (v) => update(index, { concentrationBasis: v })), select("状态", item.status, ["active", "historical", "unavailable"], (v) => update(index, { status: v }))])); }
function renderLinks(items: Link[], risks: any[], theses: any[], update: (index: number, patch: Partial<Link>) => void, add: () => void, remove: (index: number) => void) { return renderCards("风险—命题人工复核", "新增关联", items, add, remove, (item, index) => h("div", { class: "risk-grid" }, [select("风险", item.riskId, ["", ...risks.map((x) => x.riskId)], (v) => update(index, { riskId: v })), select("命题", item.thesisId, ["", ...theses.filter((x) => x.epistemicType === "system_judgment").map((x) => x.thesisId)], (v) => update(index, { thesisId: v })), select("关系", item.relationship, ["invalidates", "pressures", "monitors"], (v) => update(index, { relationship: v })), textarea("关联及复核理由", item.rationale, (v) => update(index, { rationale: v }), true)])); }
function renderCards<T>(title: string, addLabel: string, items: T[], add: () => void, remove: (index: number) => void, render: (item: T, index: number) => ReturnType<typeof h>) { return h("section", { class: "mt-3" }, [h("div", { class: "risk-card-header" }, [h("h3", { class: "h6 mb-0" }, `${title}（${items.length}）`), h("button", { onClick: add }, addLabel)]), ...items.map((item, index) => h("article", { class: "risk-card" }, [h("div", { class: "risk-card-header" }, [h("h4", `${title} ${index + 1}`), items.length > 1 ? h("button", { class: "risk-delete", onClick: () => remove(index) }, "删除") : h("span")]), render(item, index)]))]); }
function input(label: string, value: string, update: (value: string) => void, type = "text", wide = false) { return h("label", { class: wide ? "wide" : "" }, [label, h("input", { type, value, onInput: (e: Event) => update((e.target as HTMLInputElement).value) })]); }
function textarea(label: string, value: string, update: (value: string) => void, wide = false) { return h("label", { class: wide ? "wide" : "" }, [label, h("textarea", { value, onInput: (e: Event) => update((e.target as HTMLTextAreaElement).value) })]); }
function select(label: string, value: string, options: string[], update: (value: string) => void) { return h("label", [label, h("select", { value, onChange: (e: Event) => update((e.target as HTMLSelectElement).value) }, options.map((option) => h("option", { value: option }, option || "请选择")))]); }
function sourceReferences(value: Source) { const url = required(value.url, "来源链接"); return [{ sourceKind: "external_url", url, title: value.title.trim() || url, publishedAt: Date.now() }]; }
function pressurePayload(item: Pressure, scenarioId: string, now: number, refs: any[]) { return { scenarioId, scenarioKey: required(item.scenarioKey, "情景键"), version: integer(item.version, "版本"), status: "draft", scope: item.scope, title: required(item.title, "标题"), transmission: required(item.transmission, "传导链"), modelVersion: required(item.modelVersion, "模型版本"), inputs: [inputRecord("revenue", "收入", item.revenueBase, item.revenueStress, "CNYm", refs), inputRecord("ebit_margin", "EBIT 利润率", item.marginBase, item.marginStress, "ratio", refs)], results: [{ key: "researcher_stated_effect", label: "研究者陈述影响", value: number(item.resultValue, "结果数值"), unit: "CNYm", explanation: required(item.resultExplanation, "结果说明") }], sourceReferences: refs, asOf: now, createdAt: now, updatedAt: now }; }
function relationshipPayload(item: Relationship, now: number, refs: any[]) { const concentration = item.concentration.trim() ? ratio(item.concentration, "集中度") : null; return { relationshipType: item.type, counterpartyName: required(item.counterparty, "对手方"), description: required(item.description, "关系说明"), transmission: required(item.transmission, "风险传导"), concentrationValue: concentration, concentrationBasis: concentration === null ? null : required(item.concentrationBasis, "集中度口径"), status: item.status, scope: item.scope, epistemicType: "observed_fact", sourceReferences: refs, asOf: now, createdAt: now, updatedAt: now }; }
function linkPayload(item: Link, now: number, refs: any[]) { return { riskId: required(item.riskId, "风险"), thesisId: required(item.thesisId, "命题"), relationship: item.relationship, rationale: required(item.rationale, "关联说明"), sourceReferences: refs, createdAt: now }; }
function inputRecord(key: string, label: string, baseline: string, stressed: string, unit: string, sourceReferences: any[]) { return { key, label, baseline: number(baseline, `${label}基准`), stressed: number(stressed, `${label}压力`), unit, epistemicType: "observed_fact", sourceReferences }; }
function required(value: string, label: string) { const result = value.trim(); if (!result) throw new Error(`${label}不能为空`); return result; }
function number(value: string, label: string) { const result = Number(value); if (!Number.isFinite(result)) throw new Error(`${label}必须为有限数值`); return result; }
function integer(value: string, label: string) { const result = number(value, label); if (!Number.isInteger(result) || result <= 0) throw new Error(`${label}必须为正整数`); return result; }
function ratio(value: string, label: string) { const result = number(value, label) / 100; if (result < 0 || result > 1) throw new Error(`${label}必须在 0–100%`); return result; }
