import { defineComponent, h, onMounted, ref } from "vue";

type Candidate = { candidateId: string; documentId: string; title: string; publishedAt: string; documentUrl: string; reportPeriod: string | null; candidateSignals: string[]; latestReview: { reviewId: string; decision: string; originalDocumentId: string | null; affectedScope: string | null; reviewer: string; reason: string; reviewedAt: number } | null };

async function responseJson(response: Response, action: string): Promise<any> {
  const raw = await response.text();
  try { return JSON.parse(raw); }
  catch { throw new Error(`${action}：本地服务返回非 JSON 响应（HTTP ${response.status}）；请检查 Worker 运行日志。未据此改变审核、正式实际、校准或估值记录。`); }
}

/** Candidates and completed reviews remain readable; local scan/review writes stay collapsed. */
export const StatutoryRevisionCandidatesPanel = defineComponent({
  name: "StatutoryRevisionCandidatesPanel",
  props: { securityCode: { type: String, required: true }, canWrite: { type: Boolean, default: false } },
  setup(props) {
    const items = ref<Candidate[]>([]); const loading = ref(false); const verifyingId = ref(""); const error = ref(""); const notice = ref(""); const verificationOutcome = ref<"" | "appended" | "blocked">("");
    const decisions = ref<Record<string, string>>({}); const reasons = ref<Record<string, string>>({}); const originals = ref<Record<string, string>>({}); const scopes = ref<Record<string, string>>({});
    const base = () => `/api/research/company/${encodeURIComponent(props.securityCode)}/statutory-disclosure-revision-candidates`;
    const load = async () => { loading.value = true; error.value = ""; try { const response = await fetch(base()); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "读取法定修订候选失败"); items.value = Array.isArray(body.data.items) ? body.data.items : []; } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { loading.value = false; } };
    const refresh = async () => { loading.value = true; error.value = ""; try { const response = await fetch(`${base()}/refresh`, { method: "POST" }); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "扫描法定修订候选失败"); notice.value = `已扫描 ${body.data.scannedDocumentCount} 份官方索引文件，识别 ${body.data.matchedCount} 个待审核候选。`; await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { loading.value = false; } };
    const review = async (item: Candidate) => { const decision = decisions.value[item.candidateId] || "needs_evidence"; const reason = reasons.value[item.candidateId]?.trim(); if (!reason) { error.value = "审核理由必填。"; return; } try { const response = await fetch(`${base()}/${encodeURIComponent(item.candidateId)}/reviews`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, reason, originalDocumentId: originals.value[item.candidateId] || null, affectedScope: scopes.value[item.candidateId] || null }) }); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "保存法定修订审核失败"); notice.value = "已追加审核记录；未自动替换主财报、正式实际或估值。"; await load(); } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } };
    const verify = async (item: Candidate) => { verifyingId.value = item.candidateId; error.value = ""; notice.value = ""; verificationOutcome.value = ""; try { const response = await fetch(`${base()}/${encodeURIComponent(item.candidateId)}/financial-statutory-verifications/refresh`, { method: "POST" }); const body = await responseJson(response, "法定重述字段核验"); if (!response.ok || body.code !== 200) { if (response.status === 409) { verificationOutcome.value = "blocked"; throw new Error(`未追加字段核验：${body.msg || "当前主源条件未满足"}。审核记录与官方原文保持不变；未创建正式实际、校准或估值。`); } throw new Error(body.msg || "法定重述字段核验失败"); } const outcomes = body.data?.outcomes || {}; verificationOutcome.value = "appended"; notice.value = `已追加 ${body.data?.createdCount || 0} 条重述字段核验：匹配 ${outcomes.match || 0}、冲突 ${outcomes.conflict || 0}、未核验 ${outcomes.unverified || 0}。不会自动创建正式实际。`; } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { verifyingId.value = ""; } };
    onMounted(() => { void load(); });
    const scanWorkbench = () => props.canWrite ? h("details", { "data-research-workbench": "statutory-revision-candidates" }, [h("summary", { class: "btn btn-outline-secondary btn-sm" }, "本地工作台：扫描官方索引"), h("div", { class: "mt-2" }, h("button", { class: "btn btn-outline-secondary btn-sm", disabled: loading.value, onClick: () => void refresh() }, loading.value ? "扫描中…" : "扫描官方索引"))]) : null;
    const reviewWorkbench = (item: Candidate) => h("details", { class: "mt-2", "data-research-workbench": "statutory-revision-review" }, [h("summary", { class: "btn btn-outline-secondary btn-sm" }, "本地工作台：追加人工审核"), h("div", { class: "composer-grid mt-3" }, [
      h("label", ["审核决定", h("select", { value: decisions.value[item.candidateId] || "needs_evidence", onChange: (event: Event) => { decisions.value[item.candidateId] = (event.target as HTMLSelectElement).value; } }, [h("option", { value: "needs_evidence" }, "需要更多证据"), h("option", { value: "not_financial_correction" }, "非财务更正"), h("option", { value: "confirmed_financial_restatement" }, "确认财务重述")])]),
      h("label", ["审核理由", h("input", { value: reasons.value[item.candidateId] || "", onInput: (event: Event) => { reasons.value[item.candidateId] = (event.target as HTMLInputElement).value; } })]),
      (decisions.value[item.candidateId] || "needs_evidence") === "confirmed_financial_restatement" ? h("label", ["被修订原始文件 ID", h("input", { value: originals.value[item.candidateId] || "", onInput: (event: Event) => { originals.value[item.candidateId] = (event.target as HTMLInputElement).value; } })]) : null,
      (decisions.value[item.candidateId] || "needs_evidence") === "confirmed_financial_restatement" ? h("label", ["影响期间/指标", h("input", { value: scopes.value[item.candidateId] || "", onInput: (event: Event) => { scopes.value[item.candidateId] = (event.target as HTMLInputElement).value; } })]) : null,
      h("button", { class: "btn btn-primary btn-sm", onClick: () => void review(item) }, "追加审核"),
    ])]);
    const verifiedReview = (item: Candidate) => h("div", { class: "research-note mt-2 mb-0", "data-statutory-revision-review": item.latestReview!.decision }, [h("p", { class: "mb-2" }, `审核：${item.latestReview!.decision}；${item.latestReview!.reason}`), h("dl", { class: "research-meta mb-2" }, [h("dt", "审核记录"), h("dd", item.latestReview!.reviewId), h("dt", "审核人 / 时间"), h("dd", `${item.latestReview!.reviewer} · ${new Date(item.latestReview!.reviewedAt).toISOString()}`), item.latestReview!.decision === "confirmed_financial_restatement" ? h("dt", "被修订原始文件 ID") : null, item.latestReview!.decision === "confirmed_financial_restatement" ? h("dd", item.latestReview!.originalDocumentId || "审核记录缺失；不可追加字段核验") : null, item.latestReview!.decision === "confirmed_financial_restatement" ? h("dt", "已确认影响范围") : null, item.latestReview!.decision === "confirmed_financial_restatement" ? h("dd", item.latestReview!.affectedScope || "审核记录缺失；不可追加字段核验") : null]), item.latestReview!.decision === "confirmed_financial_restatement" && props.canWrite ? h("details", { class: "mt-2", "data-research-workbench": "statutory-revision-verification" }, [h("summary", { class: "btn btn-outline-primary btn-sm" }, "本地工作台：以该修订原文追加字段核验"), h("div", { class: "mt-2" }, h("button", { class: "btn btn-outline-primary btn-sm", disabled: verifyingId.value === item.candidateId, onClick: () => void verify(item) }, verifyingId.value === item.candidateId ? "字段核验中…" : "运行字段核验"))]) : null, item.latestReview!.decision === "confirmed_financial_restatement" ? h("p", { class: "research-meta mt-2 mb-0" }, "只比较当前 Eastmoney 主事实；主源未同步时会保持冲突/阻断，不会自动创建正式实际。") : null]);
    return () => h("section", { class: "research-card", "data-statutory-revision-candidates": "true" }, [
      h("div", { class: "section-head" }, [h("div", [h("h2", "法定披露更正/修订候选"), h("p", { class: "research-meta mb-0" }, "标题规则只识别待审核候选；同日披露不会被猜测成财务重述，也不会替代 Eastmoney 主源。")]), scanWorkbench()]),
      notice.value ? h("div", { class: "alert alert-success py-2 mt-3 mb-0", "data-restatement-verification-outcome": verificationOutcome.value || "appended" }, notice.value) : null, error.value ? h("div", { class: "alert alert-danger py-2 mt-3 mb-0", "data-restatement-verification-outcome": verificationOutcome.value || "error" }, error.value) : null,
      !loading.value && !items.value.length ? h("p", { class: "research-note mt-3 mb-0" }, "当前未发现需要审核的官方更正/修订候选；这不等于已证明不存在重述。") : null,
      items.value.map((item) => h("article", { class: "record", "data-statutory-revision-candidate": item.candidateId }, [h("div", { class: "section-head" }, [h("strong", item.title), h("span", { class: "research-state" }, item.latestReview ? item.latestReview.decision : "candidate")]), h("p", { class: "research-meta" }, `${item.publishedAt} · 报告期 ${item.reportPeriod || "未能从标题确定"} · 信号 ${item.candidateSignals.join("、")}`), h("a", { href: item.documentUrl, target: "_blank", rel: "noreferrer", class: "evidence-link" }, "打开官方原文"), item.latestReview ? verifiedReview(item) : props.canWrite ? reviewWorkbench(item) : h("p", { class: "research-note mt-2 mb-0" }, "生产环境只读；候选必须在本地人工审核。")]))
    ]);
  },
});
