import { defineComponent, h, ref } from "vue";
import { calculateDcf, calculateDcfSensitivity, calculateReverseDcfFromSecurity, type OperatingForecastYear, type ReverseDcfSecurityResult } from "../../../../../src/modules/research/domain/research-valuation";

type Row = { fiscalYear: string; revenue: string; ebitMargin: string; taxRate: string; depreciationAmortization: string; capitalExpenditure: string; changeInNetWorkingCapital: string };
const styles = `.valuation-workbench{margin-top:1rem}.valuation-form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.6rem}.valuation-form-grid label{display:block;font-size:.76rem;color:#365653}.valuation-form-grid input{width:100%;border:1px solid #c6d5d2;border-radius:.4rem;padding:.4rem;margin-top:.2rem}.valuation-row{border-top:1px solid #dbe7e5;padding:.7rem 0}.valuation-result{background:#effaf8;border:1px solid #9bcfc5;border-radius:.75rem;padding:.8rem}.valuation-result-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.6rem}.valuation-result-grid article{background:#fff;border-radius:.5rem;padding:.55rem}@media(max-width:800px){.valuation-form-grid,.valuation-result-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.valuation-form-grid,.valuation-result-grid{grid-template-columns:1fr}}`;

export const ValuationWorkbench = defineComponent({
  name: "ValuationWorkbench",
  props: { securityCode: { type: String, required: true }, canWrite: { type: Boolean, default: false }, securityCurrency: { type: String, default: "" }, underlyingSharesPerSecurity: { type: Number, default: 1 } },
  setup(props) {
    const currency = ref("CNY"); const securityCurrency = ref(props.securityCurrency || "CNY"); const amountScale = ref("与输入预测相同的明确单位"); const wacc = ref("10"); const terminalGrowth = ref("3"); const netDebt = ref(""); const netDebtSourceUrl = ref(""); const dilutedShares = ref(""); const dilutedSharesSourceUrl = ref(""); const underlyingRatio = ref(String(props.underlyingSharesPerSecurity || 1)); const fxRate = ref(""); const fxSourceUrl = ref("");
    const rows = ref<Row[]>([emptyRow(String(new Date().getFullYear() + 1)), emptyRow(String(new Date().getFullYear() + 2))]);
    const result = ref<ReturnType<typeof calculateDcf> | null>(null); const sensitivity = ref<ReturnType<typeof calculateDcfSensitivity> | null>(null); const error = ref(""); const saving = ref(false); const saved = ref("");
    const reversePrice = ref(""); const reversePriceAsOf = ref(new Date().toISOString().slice(0, 16)); const reversePriceSourceUrl = ref(""); const reverseDilutedShares = ref(""); const reverseDilutedSharesScale = ref("million shares"); const reverseDilutedSharesSourceUrl = ref(""); const reverseNetDebt = ref(""); const reverseNetDebtSourceUrl = ref(""); const reverseWacc = ref("10"); const reverseTerminalGrowth = ref("3"); const reverseUfcfMargin = ref(""); const reverseEbitMargin = ref(""); const reverseFxRate = ref(""); const reverseFxSourceUrl = ref(""); const reverseResult = ref<ReverseDcfSecurityResult | null>(null); const reverseSaving = ref(false); const reverseSaved = ref(""); const reverseError = ref("");
    const update = (index: number, key: keyof Row, value: string) => { rows.value = rows.value.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row); };
    const calculate = () => { error.value = ""; try { const forecasts = rows.value.map(toForecast); const assumptions = { currency: currency.value, wacc: percent(wacc.value), terminalGrowth: percent(terminalGrowth.value), netDebt: number(netDebt.value), dilutedShares: number(dilutedShares.value) }; result.value = calculateDcf(forecasts, assumptions); sensitivity.value = calculateDcfSensitivity(forecasts, assumptions, [assumptions.wacc, assumptions.wacc + 0.01, assumptions.wacc + 0.02], [Math.max(-0.99, assumptions.terminalGrowth - 0.02), Math.max(-0.99, assumptions.terminalGrowth - 0.01), assumptions.terminalGrowth]); } catch (reason) { result.value = null; sensitivity.value = null; error.value = reason instanceof Error ? reason.message : String(reason); } };
    const saveVersion = async () => { if (!result.value) return; saving.value = true; error.value = ""; saved.value = ""; try { const sameCurrency = currency.value.trim().toUpperCase() === securityCurrency.value.trim().toUpperCase(); const fx = sameCurrency ? null : number(fxRate.value); const fxRefs = sameCurrency ? [] : [{ sourceKind: "external_url", url: requiredUrl(fxSourceUrl.value), title: "FX source" }]; const assumptions = { wacc: percent(wacc.value), terminalGrowth: percent(terminalGrowth.value), netDebt: number(netDebt.value), dilutedShares: number(dilutedShares.value) }; const response = await fetch(`/api/research/company/${encodeURIComponent(props.securityCode)}/valuation-models/dcf`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: "draft", valuationCurrency: currency.value, amountScale: amountScale.value, securityCurrency: securityCurrency.value, fxRateToSecurity: fx, fxAsOf: sameCurrency ? null : Date.now(), fxSourceReferences: fxRefs, underlyingSharesPerSecurity: number(underlyingRatio.value), inputs: [input("wacc", "WACC", assumptions.wacc, "ratio"), input("terminal_growth", "永续增长", assumptions.terminalGrowth, "ratio"), observedInput("net_debt", "净债务", assumptions.netDebt, amountScale.value, netDebtSourceUrl.value), observedInput("diluted_shares", "稀释后股数", assumptions.dilutedShares, "shares", dilutedSharesSourceUrl.value)], operatingForecasts: rows.value.map(toForecast), sourceReferences: [] }) }); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "保存模型版本失败"); saved.value = `已保存不可变 DCF 版本：${body.data.modelVersionId}`; } catch (reason) { error.value = reason instanceof Error ? reason.message : String(reason); } finally { saving.value = false; } };
    const reverseInput = () => { const sameCurrency = currency.value.trim().toUpperCase() === securityCurrency.value.trim().toUpperCase(); return { status: "draft", valuationCurrency: currency.value, amountScale: amountScale.value, securityCurrency: securityCurrency.value, pricePerSecurity: number(reversePrice.value), priceAsOf: timestamp(reversePriceAsOf.value, "市场价格日期"), priceSourceReferences: [externalReference(reversePriceSourceUrl.value, "市场价格来源")], dilutedUnderlyingShares: number(reverseDilutedShares.value), dilutedSharesScale: requiredText(reverseDilutedSharesScale.value, "稀释后股数单位"), dilutedSharesSourceReferences: [externalReference(reverseDilutedSharesSourceUrl.value, "稀释后股数来源")], underlyingSharesPerSecurity: number(underlyingRatio.value), netDebtAtValuation: number(reverseNetDebt.value), netDebtSourceReferences: [externalReference(reverseNetDebtSourceUrl.value, "净债务来源")], fxRateToValuation: sameCurrency ? null : number(reverseFxRate.value), fxAsOf: sameCurrency ? null : timestamp(reversePriceAsOf.value, "FX 日期"), fxSourceReferences: sameCurrency ? [] : [externalReference(reverseFxSourceUrl.value, "FX 来源")], wacc: percent(reverseWacc.value), terminalGrowth: percent(reverseTerminalGrowth.value), terminalFreeCashFlowMargin: optionalPercent(reverseUfcfMargin.value), terminalEbitMargin: optionalPercent(reverseEbitMargin.value), assumptionSourceReferences: [] }; };
    const calculateReverse = () => { reverseError.value = ""; reverseSaved.value = ""; try { const input = reverseInput(); reverseResult.value = calculateReverseDcfFromSecurity(input); } catch (reason) { reverseResult.value = null; reverseError.value = reason instanceof Error ? reason.message : String(reason); } };
    const saveReverse = async () => { if (!reverseResult.value) return; reverseSaving.value = true; reverseError.value = ""; reverseSaved.value = ""; try { const response = await fetch(`/api/research/company/${encodeURIComponent(props.securityCode)}/valuation-models/reverse-dcf`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(reverseInput()) }); const body = await response.json(); if (!response.ok || body.code !== 200) throw new Error(body.msg || "保存反向估值版本失败"); reverseSaved.value = `已保存反向 DCF 版本：${body.data.modelVersionId}`; } catch (reason) { reverseError.value = reason instanceof Error ? reason.message : String(reason); } finally { reverseSaving.value = false; } };
    return () => h("section", { class: "research-card valuation-workbench" }, [h("style", styles), h("div", { class: "section-head" }, [h("div", [h("h2", "确定性 DCF / 反向估值工作台"), h("p", { class: "research-meta mb-0" }, "只计算你明确填写的同币种经营预测；不会抓取、猜测或覆盖来源事实。预览结果需作为带认识类型和证据的估值案例另行保存。")]), h("span", { class: "research-state" }, "模型预览")]),
      h("div", { class: "valuation-form-grid mt-3" }, [field("估值币种", currency.value, (value) => { currency.value = value; }), field("证券交易币种", securityCurrency.value, (value) => { securityCurrency.value = value; }), field("数值单位", amountScale.value, (value) => { amountScale.value = value; }), field("每份证券对应基础股数", underlyingRatio.value, (value) => { underlyingRatio.value = value; }, "number"), field("WACC（%）", wacc.value, (value) => { wacc.value = value; }, "number"), field("永续增长（%）", terminalGrowth.value, (value) => { terminalGrowth.value = value; }, "number"), field("净债务（与收入同一数值单位）", netDebt.value, (value) => { netDebt.value = value; }, "number"), field("净债务法定来源链接", netDebtSourceUrl.value, (value) => { netDebtSourceUrl.value = value; }, "url"), field("稀释后股数（明确单位）", dilutedShares.value, (value) => { dilutedShares.value = value; }, "number"), field("稀释后股数法定来源链接", dilutedSharesSourceUrl.value, (value) => { dilutedSharesSourceUrl.value = value; }, "url"), currency.value.trim().toUpperCase() !== securityCurrency.value.trim().toUpperCase() ? field("估值币种→证券币种 FX", fxRate.value, (value) => { fxRate.value = value; }, "number") : null, currency.value.trim().toUpperCase() !== securityCurrency.value.trim().toUpperCase() ? field("FX 来源链接", fxSourceUrl.value, (value) => { fxSourceUrl.value = value; }, "url") : null]),
      h("p", { class: "research-meta mt-3 mb-1" }, "逐年经营预测：收入、D&A、capex、净营运资本变动、净债务和股数必须使用同一币种与数值单位；负净债务请显式输入负数。"),
      rows.value.map((row, index) => h("div", { class: "valuation-row" }, [h("strong", `预测年度 ${index + 1}`), h("div", { class: "valuation-form-grid mt-2" }, [
        field("财年", row.fiscalYear, (value) => update(index, "fiscalYear", value), "number"), field("收入", row.revenue, (value) => update(index, "revenue", value), "number"), field("EBIT 利润率（%）", row.ebitMargin, (value) => update(index, "ebitMargin", value), "number"), field("税率（%）", row.taxRate, (value) => update(index, "taxRate", value), "number"), field("D&A", row.depreciationAmortization, (value) => update(index, "depreciationAmortization", value), "number"), field("资本开支", row.capitalExpenditure, (value) => update(index, "capitalExpenditure", value), "number"), field("净营运资本变动", row.changeInNetWorkingCapital, (value) => update(index, "changeInNetWorkingCapital", value), "number"),
      ])])), h("button", { class: "btn btn-outline-secondary btn-sm", onClick: () => { const next = Number(rows.value.at(-1)?.fiscalYear || new Date().getFullYear()) + 1; rows.value = [...rows.value, emptyRow(String(next))]; } }, "增加预测年度"), h("button", { class: "btn btn-success btn-sm ms-2", onClick: calculate }, "计算企业价值与每股价值"), result.value && props.canWrite ? h("button", { class: "btn btn-outline-primary btn-sm ms-2", disabled: saving.value, onClick: () => void saveVersion() }, saving.value ? "保存中…" : "保存为不可变模型版本") : null,
      error.value ? h("div", { class: "alert alert-danger py-2 mt-3 mb-0" }, error.value) : null,
      saved.value ? h("div", { class: "alert alert-success py-2 mt-3 mb-0" }, saved.value) : null,
      result.value ? renderResult(result.value, sensitivity.value) : h("div", { class: "research-note mt-3" }, "尚未计算。若 WACC 不高于永续增长、预测年度不连续、币种/单位不一致或缺少稀释股数，模型会拒绝给出结果。"),
      h("section", { class: "valuation-result mt-3" }, [h("strong", "反向 DCF：明确市场价格隐含的终值条件"), h("p", { class: "research-meta mt-2" }, "不会自动读取行情、股本或 FX。必须填写有日期和来源的价格、稀释后基础股数及其倍率、估值日净债务；ADR/存托证券须填写每份证券对应的基础股数。仅在明确给出终值 UFCF 利润率时，才会推导终值收入。"), h("div", { class: "valuation-form-grid mt-2" }, [field("每份证券市场价格", reversePrice.value, (value) => { reversePrice.value = value; }, "number"), field("价格日期", reversePriceAsOf.value, (value) => { reversePriceAsOf.value = value; }, "datetime-local"), field("市场价格来源链接", reversePriceSourceUrl.value, (value) => { reversePriceSourceUrl.value = value; }, "url"), field("稀释后基础股数", reverseDilutedShares.value, (value) => { reverseDilutedShares.value = value; }, "number"), field("股数倍率/单位（如 million shares）", reverseDilutedSharesScale.value, (value) => { reverseDilutedSharesScale.value = value; }), field("稀释后股数来源链接", reverseDilutedSharesSourceUrl.value, (value) => { reverseDilutedSharesSourceUrl.value = value; }, "url"), field("估值日净债务", reverseNetDebt.value, (value) => { reverseNetDebt.value = value; }, "number"), field("净债务来源链接", reverseNetDebtSourceUrl.value, (value) => { reverseNetDebtSourceUrl.value = value; }, "url"), field("反向 WACC（%）", reverseWacc.value, (value) => { reverseWacc.value = value; }, "number"), field("反向永续增长（%）", reverseTerminalGrowth.value, (value) => { reverseTerminalGrowth.value = value; }, "number"), field("终值 UFCF 利润率（%，可选）", reverseUfcfMargin.value, (value) => { reverseUfcfMargin.value = value; }, "number"), field("终值 EBIT 利润率（%，可选）", reverseEbitMargin.value, (value) => { reverseEbitMargin.value = value; }, "number"), currency.value.trim().toUpperCase() !== securityCurrency.value.trim().toUpperCase() ? field("证券币种→估值币种 FX", reverseFxRate.value, (value) => { reverseFxRate.value = value; }, "number") : null, currency.value.trim().toUpperCase() !== securityCurrency.value.trim().toUpperCase() ? field("FX 来源链接", reverseFxSourceUrl.value, (value) => { reverseFxSourceUrl.value = value; }, "url") : null]), h("button", { class: "btn btn-success btn-sm mt-3", onClick: calculateReverse }, "计算市场隐含条件"), reverseResult.value && props.canWrite ? h("button", { class: "btn btn-outline-primary btn-sm mt-3 ms-2", disabled: reverseSaving.value, onClick: () => void saveReverse() }, reverseSaving.value ? "保存中…" : "保存反向 DCF 版本") : null, reverseError.value ? h("div", { class: "alert alert-danger py-2 mt-3 mb-0" }, reverseError.value) : null, reverseSaved.value ? h("div", { class: "alert alert-success py-2 mt-3 mb-0" }, reverseSaved.value) : null, reverseResult.value ? renderReverseResult(reverseResult.value, amountScale.value) : null]),
    ]);
  },
});

function emptyRow(fiscalYear: string): Row { return { fiscalYear, revenue: "", ebitMargin: "", taxRate: "", depreciationAmortization: "", capitalExpenditure: "", changeInNetWorkingCapital: "" }; }
function field(label: string, value: string, update: (value: string) => void, type = "text") { return h("label", [label, h("input", { type, value, onInput: (event: Event) => update((event.target as HTMLInputElement).value) })]); }
function number(value: string) { const parsed = Number(value); if (!Number.isFinite(parsed)) throw new Error("all monetary inputs must be finite numbers"); return parsed; }
function requiredText(value: string, label: string) { const result = value.trim(); if (!result) throw new Error(`${label}不能为空`); return result; }
function input(key: string, label: string, value: number, unit: string) { return { key, label, value, unit, epistemicType: "analysis_assumption", sourceReferences: [] }; }
function observedInput(key: string, label: string, value: number, unit: string, url: string) { return { key, label, value, unit, epistemicType: "observed_fact", sourceReferences: [{ sourceKind: "external_url", url: requiredUrl(url), title: label }] }; }
function requiredUrl(value: string) { const url = value.trim(); if (!/^https?:\/\//i.test(url)) throw new Error("cross-currency FX requires an http(s) source URL"); return url; }
function externalReference(url: string, title: string) { return { sourceKind: "external_url", url: requiredUrl(url), title }; }
function timestamp(value: string, label: string) { const result = Date.parse(value); if (!Number.isFinite(result) || result <= 0) throw new Error(`${label}必须为有效日期`); return result; }
function optionalPercent(value: string) { return value.trim() ? percent(value) : null; }
function percent(value: string) { return number(value) / 100; }
function toForecast(row: Row): OperatingForecastYear { return { fiscalYear: Number(row.fiscalYear), revenue: number(row.revenue), ebitMargin: percent(row.ebitMargin), taxRate: percent(row.taxRate), depreciationAmortization: number(row.depreciationAmortization), capitalExpenditure: number(row.capitalExpenditure), changeInNetWorkingCapital: number(row.changeInNetWorkingCapital) }; }
function formatted(value: number, currency: string) { return `${value.toLocaleString("zh-CN", { maximumFractionDigits: 2 })} ${currency}`; }
function renderResult(result: ReturnType<typeof calculateDcf>, sensitivity: ReturnType<typeof calculateDcfSensitivity> | null) {
  return h("div", { class: "valuation-result mt-3" }, [h("strong", "计算结果（模型预览，不是投资结论）"), h("div", { class: "valuation-result-grid mt-2" }, [value("企业价值", formatted(result.enterpriseValue, result.currency)), value("股权价值", formatted(result.equityValue, result.currency)), value("每股价值", formatted(result.valuePerShare, result.currency)), value("终值现值", formatted(result.terminalPresentValue, result.currency))]), h("p", { class: "research-meta mt-3 mb-1" }, result.formula), h("div", { class: "research-meta" }, `敏感性已围绕当前 WACC/永续增长各 ±1 个百分点计算 ${sensitivity ? sensitivity.length * sensitivity[0].values.length : 0} 个严格可行组合；将来保存时需将每个关键假设的来源和认识类型一并写入。`)]); }
function renderReverseResult(result: ReverseDcfSecurityResult, amountScale: string) { return h("div", { class: "valuation-result mt-3" }, [h("strong", "市场隐含条件（不是价格预测或交易建议）"), h("div", { class: "valuation-result-grid mt-2" }, [value("市场资本化", formatted(result.marketCapitalizationInSecurityCurrency, result.securityCurrency)), value("转换后股权价值", formatted(result.equityValue, result.currency)), value("隐含企业价值", formatted(result.enterpriseValue, result.currency)), value("隐含终值 UFCF", formatted(result.impliedTerminalUnleveredFreeCashFlow, result.currency)), value("隐含终值收入", result.impliedTerminalRevenue === null ? "未给终值 UFCF 利润率" : formatted(result.impliedTerminalRevenue, result.currency)), value("隐含终值 EBIT", result.impliedTerminalEbit === null ? "需同时给终值 UFCF/EBIT 利润率" : formatted(result.impliedTerminalEbit, result.currency))]), h("p", { class: "research-meta mt-3 mb-0" }, `${result.formula} 所有金额使用 ${amountScale}。`)]); }
function value(label: string, content: string) { return h("article", [h("div", { class: "research-meta" }, label), h("strong", content)]); }
