#!/usr/bin/env node

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(SCRIPT_DIR, "..");

const promptEntries = [
  {
    exportName: "REPORT_ANALYZE_SYSTEM_PROMPT",
    source: "prompts/company/report-analyze-system.md",
  },
  {
    exportName: "REPORT_ANALYZE_USER_PROMPT",
    source: "prompts/company/report-analyze-user.md",
  },
  {
    exportName: "REPORT_DISCOVERY_PROMPT",
    source: "prompts/company/report-discovery.md",
  },
  {
    exportName: "TOPIC_BATCH_SYSTEM_PROMPT",
    source: "prompts/knowledge/topic-batch-system.md",
  },
  {
    exportName: "TOPIC_BATCH_USER_PROMPT",
    source: "prompts/knowledge/topic-batch-user.md",
  },
  {
    exportName: "INFORMATION_PROCESSING_DOCUMENT_ANALYSIS_SYSTEM_PROMPT",
    source: "prompts/information-processing/document-analysis-system.md",
  },
  {
    exportName: "INFORMATION_PROCESSING_DOCUMENT_ANALYSIS_USER_PROMPT",
    source: "prompts/information-processing/document-analysis-user.md",
  },
  {
    exportName: "RESEARCH_FORECAST_SYNTHESIS_SYSTEM_PROMPT",
    source: "prompts/research/forecast-synthesis-system.md",
  },
  {
    exportName: "RESEARCH_FORECAST_SYNTHESIS_USER_PROMPT",
    source: "prompts/research/forecast-synthesis-user.md",
  },
  {
    exportName: "RESEARCH_FINANCIAL_ANALYSIS_PROMPT",
    source: "prompts/research/financial-analysis.md",
  },
  {
    exportName: "RESEARCH_OPERATING_ANALYSIS_PROMPT",
    source: "prompts/research/operating-analysis.md",
  },
  {
    exportName: "RESEARCH_OPERATING_ANALYSIS_SYSTEM_PROMPT",
    source: "prompts/research/operating-analysis-system.md",
  },
];

const generatedTsPath = resolve(PROJECT_ROOT, "src/generated/prompt-text.ts");
const generatedMjsPath = resolve(PROJECT_ROOT, "scripts/generated/prompt-text.mjs");

const lines = [
  "// Generated by scripts/build-prompts.mjs. Do not edit by hand.",
  "",
];

for (const entry of promptEntries) {
  const text = readFileSync(resolve(PROJECT_ROOT, entry.source), "utf8").trim();
  lines.push(`export const ${entry.exportName} = ${JSON.stringify(text)};`);
}

lines.push("");

const output = `${lines.join("\n")}`;

mkdirSync(dirname(generatedTsPath), { recursive: true });
mkdirSync(dirname(generatedMjsPath), { recursive: true });
writeFileSync(generatedTsPath, output);
writeFileSync(generatedMjsPath, output);
