import {
  assertResearchMarketSpaceAssessment, assertResearchOperatingDriverPlan, assertResearchOperatingModel,
  type ResearchContractDriver, type ResearchGrowthConstraint, type ResearchMarketProfitPool, type ResearchMarketShareBridge,
  type ResearchMarketShareBridgeStep, type ResearchMarketSpaceAssessment, type ResearchMarketSpaceEstimate,
  type ResearchOperatingDriverPlan, type ResearchOperatingDriverPlanYear, type ResearchOperatingDriverSegmentYear,
  type ResearchOperatingModel, type ResearchOperatingSegment, type ResearchUnitEconomic,
} from "../domain/research-operating-market";
import type { ResearchSourceReference } from "../domain/research-dossier";

type Subject = "operating_model" | "operating_segment" | "contract_driver" | "unit_economic" | "growth_constraint" | "driver_plan" | "driver_plan_year" | "driver_segment_year" | "market_space_assessment" | "market_space_estimate" | "share_bridge" | "share_bridge_step" | "profit_pool";
export type ResearchOperatingMarketWriteResult = { state: "saved" | "unavailable"; recordId: string; reason: "storage_not_initialized" | null };
export type ResearchOperatingMarketSection<T> = { availability: "available" | "empty" | "unavailable"; reason: "identity_not_found" | "no_records" | "storage_not_initialized" | null; items: T[] };

export async function loadResearchOperatingModels(db: D1Database, query: { companyId: string | null; asOf: number }): Promise<ResearchOperatingMarketSection<ResearchOperatingModel>> {
  if (!query.companyId) return unavailable("identity_not_found");
  try {
    const rows = await db.prepare(`select * from research_operating_models_typed where company_id=? and as_of<=? and status<>'superseded' order by as_of desc, version desc, created_at desc, operating_model_id`).bind(query.companyId, query.asOf).all<Row>();
    return section(await hydrateOperatingModels(db, rows.results));
  } catch (error) { if (missing(error, "research_operating_models_typed")) return unavailable("storage_not_initialized"); throw error; }
}

export async function loadResearchOperatingDriverPlans(db: D1Database, query: { companyId: string | null; operatingModelId?: string; asOf: number }): Promise<ResearchOperatingMarketSection<ResearchOperatingDriverPlan>> {
  if (!query.companyId) return unavailable("identity_not_found");
  try {
    const rows = await db.prepare(`select p.* from research_operating_driver_plans p join research_operating_models_typed m on m.operating_model_id=p.operating_model_id where m.company_id=? and p.as_of<=? and p.status<>'superseded' and (? is null or p.operating_model_id=?) order by p.as_of desc, p.version desc, p.created_at desc, p.operating_driver_plan_id`).bind(query.companyId, query.asOf, query.operatingModelId ?? null, query.operatingModelId ?? null).all<Row>();
    return section(await hydrateDriverPlans(db, rows.results));
  } catch (error) { if (missing(error, "research_operating_driver_plans")) return unavailable("storage_not_initialized"); throw error; }
}

export async function loadResearchMarketSpaceAssessments(db: D1Database, query: { companyId: string | null; asOf: number }): Promise<ResearchOperatingMarketSection<ResearchMarketSpaceAssessment>> {
  if (!query.companyId) return unavailable("identity_not_found");
  try {
    const rows = await db.prepare(`select * from research_market_space_assessments_typed where company_id=? and as_of<=? and status<>'superseded' order by as_of desc, version desc, created_at desc, market_space_assessment_id`).bind(query.companyId, query.asOf).all<Row>();
    return section(await hydrateMarketSpaces(db, rows.results));
  } catch (error) { if (missing(error, "research_market_space_assessments_typed")) return unavailable("storage_not_initialized"); throw error; }
}

export async function insertResearchOperatingModel(db: D1Database, input: ResearchOperatingModel): Promise<ResearchOperatingMarketWriteResult> {
  assertResearchOperatingModel(input);
  const statements: D1PreparedStatement[] = [db.prepare(`insert into research_operating_models_typed (
    operating_model_id, company_id, as_of, version, status, model_type, primary_earning_driver, revenue_recognition, summary, epistemic_type, created_at, updated_at
  ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(input.operatingModelId, input.companyId, input.asOf, input.version, input.status, input.modelType, input.primaryEarningDriver, input.revenueRecognition, input.summary, input.epistemicType, input.createdAt, input.updatedAt), ...evidence(db, "operating_model", input.operatingModelId, input.sourceReferences, input.createdAt)];
  for (const segment of input.segments) {
    statements.push(db.prepare(`insert into research_operating_model_segments_typed (
      operating_segment_id, operating_model_id, name, product_scope, customer_scope, geographic_scope, revenue_formula, revenue_recognition, sort_order
    ) values (?, ?, ?, ?, ?, ?, ?, ?, ?)`)
      .bind(segment.operatingSegmentId, input.operatingModelId, segment.name, segment.productScope, segment.customerScope, segment.geographicScope, segment.revenueFormula, segment.revenueRecognition, segment.sortOrder), ...evidence(db, "operating_segment", segment.operatingSegmentId, segment.sourceReferences, input.createdAt));
    for (const contract of segment.contracts) statements.push(db.prepare(`insert into research_operating_model_contracts_typed (
      contract_driver_id, operating_segment_id, contract_type, customer_or_channel, commitment_description, pricing_basis, renewal_or_delivery_constraint, start_period, end_period, sort_order
    ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
      .bind(contract.contractDriverId, segment.operatingSegmentId, contract.contractType, contract.customerOrChannel, contract.commitmentDescription, contract.pricingBasis, contract.renewalOrDeliveryConstraint, contract.startPeriod, contract.endPeriod, contract.sortOrder), ...evidence(db, "contract_driver", contract.contractDriverId, contract.sourceReferences, input.createdAt));
    for (const unit of segment.unitEconomics) statements.push(db.prepare(`insert into research_operating_model_unit_economics_typed (
      unit_economic_id, operating_segment_id, unit_name, price_per_unit, variable_cost_per_unit, currency, amount_scale, period_basis, contribution_description, sort_order
    ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
      .bind(unit.unitEconomicId, segment.operatingSegmentId, unit.unitName, unit.pricePerUnit, unit.variableCostPerUnit, unit.currency, unit.amountScale, unit.periodBasis, unit.contributionDescription, unit.sortOrder), ...evidence(db, "unit_economic", unit.unitEconomicId, unit.sourceReferences, input.createdAt));
  }
  for (const item of input.growthConstraints) statements.push(db.prepare(`insert into research_operating_model_growth_constraints_typed (
    growth_constraint_id, operating_model_id, operating_segment_id, constraint_kind, description, affected_statement, affected_driver, invalidation_or_release_condition, sort_order
  ) values (?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(item.growthConstraintId, input.operatingModelId, item.operatingSegmentId, item.constraintKind, item.description, item.affectedStatement, item.affectedDriver, item.invalidationOrReleaseCondition, item.sortOrder), ...evidence(db, "growth_constraint", item.growthConstraintId, item.sourceReferences, input.createdAt));
  return runInsert(db, "research_operating_models_typed", input.operatingModelId, statements);
}

export async function insertResearchOperatingDriverPlan(db: D1Database, input: ResearchOperatingDriverPlan): Promise<ResearchOperatingMarketWriteResult> {
  assertResearchOperatingDriverPlan(input);
  const statements: D1PreparedStatement[] = [db.prepare(`insert into research_operating_driver_plans (
    operating_driver_plan_id, operating_model_id, scenario_name, as_of, version, status, valuation_currency, amount_scale, opening_revenue, opening_net_working_capital, epistemic_type, created_at, updated_at
  ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(input.operatingDriverPlanId, input.operatingModelId, input.scenarioName, input.asOf, input.version, input.status, input.valuationCurrency, input.amountScale, input.openingRevenue, input.openingNetWorkingCapital, input.epistemicType, input.createdAt, input.updatedAt), ...evidence(db, "driver_plan", input.operatingDriverPlanId, input.sourceReferences, input.createdAt)];
  for (const year of input.years) {
    statements.push(db.prepare(`insert into research_operating_driver_plan_years (operating_driver_plan_year_id, operating_driver_plan_id, fiscal_year, tax_rate, forecast_net_debt, sort_order) values (?, ?, ?, ?, ?, ?)`)
      .bind(year.operatingDriverPlanYearId, input.operatingDriverPlanId, year.fiscalYear, year.taxRate, year.forecastNetDebt, year.sortOrder), ...evidence(db, "driver_plan_year", year.operatingDriverPlanYearId, year.sourceReferences, input.createdAt));
    for (const segment of year.segments) statements.push(db.prepare(`insert into research_operating_driver_segment_years (
      operating_driver_segment_year_id, operating_driver_plan_year_id, operating_segment_id, volume, price_per_unit, gross_margin, operating_expense_margin, depreciation_amortization_margin, capital_expenditure_margin, net_working_capital_to_revenue, sort_order
    ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
      .bind(segment.operatingDriverSegmentYearId, year.operatingDriverPlanYearId, segment.operatingSegmentId, segment.volume, segment.pricePerUnit, segment.grossMargin, segment.operatingExpenseMargin, segment.depreciationAmortizationMargin, segment.capitalExpenditureMargin, segment.netWorkingCapitalToRevenue, segment.sortOrder), ...evidence(db, "driver_segment_year", segment.operatingDriverSegmentYearId, segment.sourceReferences, input.createdAt));
  }
  return runInsert(db, "research_operating_driver_plans", input.operatingDriverPlanId, statements);
}

export async function insertResearchMarketSpaceAssessment(db: D1Database, input: ResearchMarketSpaceAssessment): Promise<ResearchOperatingMarketWriteResult> {
  assertResearchMarketSpaceAssessment(input);
  const statements: D1PreparedStatement[] = [db.prepare(`insert into research_market_space_assessments_typed (
    market_space_assessment_id, company_id, operating_model_id, as_of, version, status, market_definition, product_boundary, geographic_boundary, customer_boundary, measurement_definition, epistemic_type, created_at, updated_at
  ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(input.marketSpaceAssessmentId, input.companyId, input.operatingModelId, input.asOf, input.version, input.status, input.marketDefinition, input.productBoundary, input.geographicBoundary, input.customerBoundary, input.measurementDefinition, input.epistemicType, input.createdAt, input.updatedAt), ...evidence(db, "market_space_assessment", input.marketSpaceAssessmentId, input.sourceReferences, input.createdAt)];
  for (const estimate of input.estimates) statements.push(db.prepare(`insert into research_market_space_estimates_typed (
    market_space_estimate_id, market_space_assessment_id, layer, method, method_basis, amount, currency, amount_scale, period_label, period_kind, calculation_description, status, sort_order
  ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(estimate.marketSpaceEstimateId, input.marketSpaceAssessmentId, estimate.layer, estimate.method, estimate.methodBasis, estimate.amount, estimate.currency, estimate.amountScale, estimate.periodLabel, estimate.periodKind, estimate.calculationDescription, estimate.status, estimate.sortOrder), ...evidence(db, "market_space_estimate", estimate.marketSpaceEstimateId, estimate.sourceReferences, input.createdAt));
  for (const bridge of input.shareBridges) {
    statements.push(db.prepare(`insert into research_market_share_bridges_typed (market_share_bridge_id, market_space_assessment_id, share_type, period_label, starting_share, ending_share, unit, status, created_at, updated_at) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
      .bind(bridge.marketShareBridgeId, input.marketSpaceAssessmentId, bridge.shareType, bridge.periodLabel, bridge.startingShare, bridge.endingShare, bridge.unit, bridge.status, bridge.createdAt, bridge.updatedAt), ...evidence(db, "share_bridge", bridge.marketShareBridgeId, bridge.sourceReferences, input.createdAt));
    for (const step of bridge.steps) statements.push(db.prepare(`insert into research_market_share_bridge_steps_typed (market_share_bridge_step_id, market_share_bridge_id, step_kind, direction, share_delta, description, sort_order) values (?, ?, ?, ?, ?, ?, ?)`)
      .bind(step.marketShareBridgeStepId, bridge.marketShareBridgeId, step.stepKind, step.direction, step.shareDelta, step.description, step.sortOrder), ...evidence(db, "share_bridge_step", step.marketShareBridgeStepId, step.sourceReferences, input.createdAt));
  }
  for (const pool of input.profitPools) statements.push(db.prepare(`insert into research_market_profit_pools_typed (market_profit_pool_id, market_space_assessment_id, period_label, industry_revenue, sustainable_operating_margin, currency, amount_scale, normalization_note, status, created_at, updated_at) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(pool.marketProfitPoolId, input.marketSpaceAssessmentId, pool.periodLabel, pool.industryRevenue, pool.sustainableOperatingMargin, pool.currency, pool.amountScale, pool.normalizationNote, pool.status, pool.createdAt, pool.updatedAt), ...evidence(db, "profit_pool", pool.marketProfitPoolId, pool.sourceReferences, input.createdAt));
  return runInsert(db, "research_market_space_assessments_typed", input.marketSpaceAssessmentId, statements);
}

type Row = Record<string, unknown>;
async function hydrateOperatingModels(db: D1Database, rows: Row[]): Promise<ResearchOperatingModel[]> {
  if (!rows.length) return [];
  const modelIds = rows.map((row) => text(row.operating_model_id));
  const [segments, constraints] = await Promise.all([byIds(db, "research_operating_model_segments_typed", "operating_model_id", modelIds), byIds(db, "research_operating_model_growth_constraints_typed", "operating_model_id", modelIds)]);
  const segmentIds = segments.map((row) => text(row.operating_segment_id));
  const [contracts, units] = await Promise.all([byIds(db, "research_operating_model_contracts_typed", "operating_segment_id", segmentIds), byIds(db, "research_operating_model_unit_economics_typed", "operating_segment_id", segmentIds)]);
  const refs = await references(db, ["operating_model", "operating_segment", "contract_driver", "unit_economic", "growth_constraint"], [...modelIds, ...segmentIds, ...contracts.map((row) => text(row.contract_driver_id)), ...units.map((row) => text(row.unit_economic_id)), ...constraints.map((row) => text(row.growth_constraint_id))]);
  const unitBySegment = group(units, "operating_segment_id", (row) => unit(row, refs)); const contractBySegment = group(contracts, "operating_segment_id", (row) => contract(row, refs));
  const segmentByModel = group(segments, "operating_model_id", (row) => segment(row, refs, contractBySegment, unitBySegment)); const constraintsByModel = group(constraints, "operating_model_id", (row) => constraint(row, refs));
  return rows.map((row) => ({ operatingModelId: text(row.operating_model_id), companyId: text(row.company_id), asOf: num(row.as_of), version: num(row.version), status: text(row.status) as ResearchOperatingModel["status"], modelType: text(row.model_type) as ResearchOperatingModel["modelType"], primaryEarningDriver: text(row.primary_earning_driver), revenueRecognition: text(row.revenue_recognition), summary: text(row.summary), epistemicType: text(row.epistemic_type) as ResearchOperatingModel["epistemicType"], sourceReferences: refs.get(key("operating_model", text(row.operating_model_id))) ?? [], segments: segmentByModel.get(text(row.operating_model_id)) ?? [], growthConstraints: constraintsByModel.get(text(row.operating_model_id)) ?? [], createdAt: num(row.created_at), updatedAt: num(row.updated_at) }));
}
async function hydrateDriverPlans(db: D1Database, rows: Row[]): Promise<ResearchOperatingDriverPlan[]> {
  if (!rows.length) return [];
  const ids = rows.map((row) => text(row.operating_driver_plan_id)); const years = await byIds(db, "research_operating_driver_plan_years", "operating_driver_plan_id", ids); const yearIds = years.map((row) => text(row.operating_driver_plan_year_id)); const segments = await byIds(db, "research_operating_driver_segment_years", "operating_driver_plan_year_id", yearIds);
  const refs = await references(db, ["driver_plan", "driver_plan_year", "driver_segment_year"], [...ids, ...yearIds, ...segments.map((row) => text(row.operating_driver_segment_year_id))]); const segmentsByYear = group(segments, "operating_driver_plan_year_id", (row) => driverSegment(row, refs)); const yearsByPlan = group(years, "operating_driver_plan_id", (row) => driverYear(row, refs, segmentsByYear));
  return rows.map((row) => ({ operatingDriverPlanId: text(row.operating_driver_plan_id), operatingModelId: text(row.operating_model_id), scenarioName: text(row.scenario_name) as ResearchOperatingDriverPlan["scenarioName"], asOf: num(row.as_of), version: num(row.version), status: text(row.status) as ResearchOperatingDriverPlan["status"], valuationCurrency: text(row.valuation_currency), amountScale: text(row.amount_scale), openingRevenue: num(row.opening_revenue), openingNetWorkingCapital: num(row.opening_net_working_capital), epistemicType: text(row.epistemic_type) as ResearchOperatingDriverPlan["epistemicType"], sourceReferences: refs.get(key("driver_plan", text(row.operating_driver_plan_id))) ?? [], years: yearsByPlan.get(text(row.operating_driver_plan_id)) ?? [], createdAt: num(row.created_at), updatedAt: num(row.updated_at) }));
}
async function hydrateMarketSpaces(db: D1Database, rows: Row[]): Promise<ResearchMarketSpaceAssessment[]> {
  if (!rows.length) return [];
  const ids = rows.map((row) => text(row.market_space_assessment_id)); const [estimates, bridges, pools] = await Promise.all([byIds(db, "research_market_space_estimates_typed", "market_space_assessment_id", ids), byIds(db, "research_market_share_bridges_typed", "market_space_assessment_id", ids, "created_at, market_share_bridge_id"), byIds(db, "research_market_profit_pools_typed", "market_space_assessment_id", ids, "created_at, market_profit_pool_id")]); const bridgeIds = bridges.map((row) => text(row.market_share_bridge_id)); const steps = await byIds(db, "research_market_share_bridge_steps_typed", "market_share_bridge_id", bridgeIds);
  const refs = await references(db, ["market_space_assessment", "market_space_estimate", "share_bridge", "share_bridge_step", "profit_pool"], [...ids, ...estimates.map((row) => text(row.market_space_estimate_id)), ...bridgeIds, ...steps.map((row) => text(row.market_share_bridge_step_id)), ...pools.map((row) => text(row.market_profit_pool_id))]); const stepsByBridge = group(steps, "market_share_bridge_id", (row) => shareStep(row, refs)); const bridgesByAssessment = group(bridges, "market_space_assessment_id", (row) => shareBridge(row, refs, stepsByBridge)); const estimatesByAssessment = group(estimates, "market_space_assessment_id", (row) => estimate(row, refs)); const poolsByAssessment = group(pools, "market_space_assessment_id", (row) => pool(row, refs));
  return rows.map((row) => ({ marketSpaceAssessmentId: text(row.market_space_assessment_id), companyId: text(row.company_id), operatingModelId: optional(row.operating_model_id), asOf: num(row.as_of), version: num(row.version), status: text(row.status) as ResearchMarketSpaceAssessment["status"], marketDefinition: text(row.market_definition), productBoundary: text(row.product_boundary), geographicBoundary: text(row.geographic_boundary), customerBoundary: text(row.customer_boundary), measurementDefinition: text(row.measurement_definition), epistemicType: text(row.epistemic_type) as ResearchMarketSpaceAssessment["epistemicType"], sourceReferences: refs.get(key("market_space_assessment", text(row.market_space_assessment_id))) ?? [], estimates: estimatesByAssessment.get(text(row.market_space_assessment_id)) ?? [], shareBridges: bridgesByAssessment.get(text(row.market_space_assessment_id)) ?? [], profitPools: poolsByAssessment.get(text(row.market_space_assessment_id)) ?? [], createdAt: num(row.created_at), updatedAt: num(row.updated_at) }));
}
function segment(row: Row, refs: Map<string, ResearchSourceReference[]>, contracts: Map<string, ResearchContractDriver[]>, units: Map<string, ResearchUnitEconomic[]>): ResearchOperatingSegment { const id = text(row.operating_segment_id); return { operatingSegmentId: id, name: text(row.name), productScope: text(row.product_scope), customerScope: text(row.customer_scope), geographicScope: text(row.geographic_scope), revenueFormula: text(row.revenue_formula), revenueRecognition: text(row.revenue_recognition), sortOrder: num(row.sort_order), sourceReferences: refs.get(key("operating_segment", id)) ?? [], contracts: contracts.get(id) ?? [], unitEconomics: units.get(id) ?? [] }; }
function contract(row: Row, refs: Map<string, ResearchSourceReference[]>): ResearchContractDriver { const id = text(row.contract_driver_id); return { contractDriverId: id, contractType: text(row.contract_type) as ResearchContractDriver["contractType"], customerOrChannel: text(row.customer_or_channel), commitmentDescription: text(row.commitment_description), pricingBasis: text(row.pricing_basis), renewalOrDeliveryConstraint: text(row.renewal_or_delivery_constraint), startPeriod: optional(row.start_period), endPeriod: optional(row.end_period), sortOrder: num(row.sort_order), sourceReferences: refs.get(key("contract_driver", id)) ?? [] }; }
function unit(row: Row, refs: Map<string, ResearchSourceReference[]>): ResearchUnitEconomic { const id = text(row.unit_economic_id); return { unitEconomicId: id, unitName: text(row.unit_name), pricePerUnit: nullableNumber(row.price_per_unit), variableCostPerUnit: nullableNumber(row.variable_cost_per_unit), currency: optional(row.currency), amountScale: optional(row.amount_scale), periodBasis: text(row.period_basis), contributionDescription: text(row.contribution_description), sortOrder: num(row.sort_order), sourceReferences: refs.get(key("unit_economic", id)) ?? [] }; }
function constraint(row: Row, refs: Map<string, ResearchSourceReference[]>): ResearchGrowthConstraint { const id = text(row.growth_constraint_id); return { growthConstraintId: id, operatingSegmentId: optional(row.operating_segment_id), constraintKind: text(row.constraint_kind) as ResearchGrowthConstraint["constraintKind"], description: text(row.description), affectedStatement: text(row.affected_statement) as ResearchGrowthConstraint["affectedStatement"], affectedDriver: text(row.affected_driver), invalidationOrReleaseCondition: text(row.invalidation_or_release_condition), sortOrder: num(row.sort_order), sourceReferences: refs.get(key("growth_constraint", id)) ?? [] }; }
function driverYear(row: Row, refs: Map<string, ResearchSourceReference[]>, segments: Map<string, ResearchOperatingDriverSegmentYear[]>): ResearchOperatingDriverPlanYear { const id = text(row.operating_driver_plan_year_id); return { operatingDriverPlanYearId: id, fiscalYear: num(row.fiscal_year), taxRate: num(row.tax_rate), forecastNetDebt: num(row.forecast_net_debt), sortOrder: num(row.sort_order), sourceReferences: refs.get(key("driver_plan_year", id)) ?? [], segments: segments.get(id) ?? [] }; }
function driverSegment(row: Row, refs: Map<string, ResearchSourceReference[]>): ResearchOperatingDriverSegmentYear { const id = text(row.operating_driver_segment_year_id); return { operatingDriverSegmentYearId: id, operatingSegmentId: text(row.operating_segment_id), volume: num(row.volume), pricePerUnit: num(row.price_per_unit), grossMargin: num(row.gross_margin), operatingExpenseMargin: num(row.operating_expense_margin), depreciationAmortizationMargin: num(row.depreciation_amortization_margin), capitalExpenditureMargin: num(row.capital_expenditure_margin), netWorkingCapitalToRevenue: num(row.net_working_capital_to_revenue), sortOrder: num(row.sort_order), sourceReferences: refs.get(key("driver_segment_year", id)) ?? [] }; }
function estimate(row: Row, refs: Map<string, ResearchSourceReference[]>): ResearchMarketSpaceEstimate { const id = text(row.market_space_estimate_id); return { marketSpaceEstimateId: id, layer: text(row.layer) as ResearchMarketSpaceEstimate["layer"], method: text(row.method) as ResearchMarketSpaceEstimate["method"], methodBasis: text(row.method_basis) as ResearchMarketSpaceEstimate["methodBasis"], amount: num(row.amount), currency: text(row.currency), amountScale: text(row.amount_scale), periodLabel: text(row.period_label), periodKind: text(row.period_kind) as ResearchMarketSpaceEstimate["periodKind"], calculationDescription: text(row.calculation_description), status: text(row.status) as ResearchMarketSpaceEstimate["status"], sortOrder: num(row.sort_order), sourceReferences: refs.get(key("market_space_estimate", id)) ?? [] }; }
function shareBridge(row: Row, refs: Map<string, ResearchSourceReference[]>, steps: Map<string, ResearchMarketShareBridgeStep[]>): ResearchMarketShareBridge { const id = text(row.market_share_bridge_id); return { marketShareBridgeId: id, shareType: text(row.share_type) as ResearchMarketShareBridge["shareType"], periodLabel: text(row.period_label), startingShare: num(row.starting_share), endingShare: num(row.ending_share), unit: text(row.unit) as ResearchMarketShareBridge["unit"], status: text(row.status) as ResearchMarketShareBridge["status"], sourceReferences: refs.get(key("share_bridge", id)) ?? [], steps: steps.get(id) ?? [], createdAt: num(row.created_at), updatedAt: num(row.updated_at) }; }
function shareStep(row: Row, refs: Map<string, ResearchSourceReference[]>): ResearchMarketShareBridgeStep { const id = text(row.market_share_bridge_step_id); return { marketShareBridgeStepId: id, stepKind: text(row.step_kind) as ResearchMarketShareBridgeStep["stepKind"], direction: text(row.direction) as ResearchMarketShareBridgeStep["direction"], shareDelta: num(row.share_delta), description: text(row.description), sortOrder: num(row.sort_order), sourceReferences: refs.get(key("share_bridge_step", id)) ?? [] }; }
function pool(row: Row, refs: Map<string, ResearchSourceReference[]>): ResearchMarketProfitPool { const id = text(row.market_profit_pool_id); return { marketProfitPoolId: id, periodLabel: text(row.period_label), industryRevenue: num(row.industry_revenue), sustainableOperatingMargin: num(row.sustainable_operating_margin), currency: text(row.currency), amountScale: text(row.amount_scale), normalizationNote: text(row.normalization_note), status: text(row.status) as ResearchMarketProfitPool["status"], sourceReferences: refs.get(key("profit_pool", id)) ?? [], createdAt: num(row.created_at), updatedAt: num(row.updated_at) }; }

/** The typed tables mostly expose an explicit sort order; bridges and profit pools
 * deliberately use append/version timestamps instead. Callers select the only
 * schema-valid deterministic ordering rather than querying a fictional column. */
async function byIds(db: D1Database, table: string, column: string, ids: string[], orderBy = "sort_order, rowid"): Promise<Row[]> { if (!ids.length) return []; const rows = await db.prepare(`select * from ${table} where ${column} in (${ids.map(() => "?").join(",")}) order by ${orderBy}`).bind(...ids).all<Row>(); return rows.results; }
async function references(db: D1Database, types: Subject[], ids: string[]): Promise<Map<string, ResearchSourceReference[]>> { if (!ids.length) return new Map(); const rows = await db.prepare(`select * from research_operating_market_evidence_refs where subject_type in (${types.map(() => "?").join(",")}) and subject_id in (${ids.map(() => "?").join(",")}) order by created_at, evidence_ref_id`).bind(...types, ...ids).all<Row>(); const output = new Map<string, ResearchSourceReference[]>(); for (const row of rows.results) { const ref: ResearchSourceReference = { sourceKind: text(row.source_kind) as ResearchSourceReference["sourceKind"], sourceId: optional(row.source_id) ?? undefined, informationId: optional(row.information_id) ?? undefined, versionId: optional(row.version_id) ?? undefined, documentId: optional(row.document_id) ?? undefined, url: optional(row.url) ?? undefined, title: optional(row.title) ?? undefined, publishedAt: optional(row.published_at) ?? undefined, locator: optional(row.locator) ?? undefined }; const mapKey = key(text(row.subject_type) as Subject, text(row.subject_id)); const items = output.get(mapKey) ?? []; items.push(ref); output.set(mapKey, items); } return output; }
function group<T>(rows: Row[], column: string, mapper: (row: Row) => T): Map<string, T[]> { const output = new Map<string, T[]>(); for (const row of rows) { const id = text(row[column]); const items = output.get(id) ?? []; items.push(mapper(row)); output.set(id, items); } return output; }
function key(subject: Subject, id: string) { return `${subject}:${id}`; }
function section<T>(items: T[]): ResearchOperatingMarketSection<T> { return items.length ? { availability: "available", reason: null, items } : { availability: "empty", reason: "no_records", items: [] }; }
function unavailable<T>(reason: "identity_not_found" | "storage_not_initialized"): ResearchOperatingMarketSection<T> { return { availability: "unavailable", reason, items: [] }; }
function missing(error: unknown, table: string) { return new RegExp(`(?:no such table|does not exist|not found).*${table}`, "i").test(error instanceof Error ? error.message : String(error)); }
function text(value: unknown): string { const result = String(value ?? "").trim(); if (!result) throw new Error("operating market record contains a required blank field"); return result; }
function optional(value: unknown): string | null { const result = String(value ?? "").trim(); return result || null; }
function num(value: unknown): number { const result = Number(value); if (!Number.isFinite(result)) throw new Error("operating market record contains a non-numeric field"); return result; }
function nullableNumber(value: unknown): number | null { return value === null || value === undefined || value === "" ? null : num(value); }
function evidence(db: D1Database, subjectType: Subject, subjectId: string, refs: ResearchSourceReference[], createdAt: number): D1PreparedStatement[] { return refs.map((ref, index) => db.prepare(`insert into research_operating_market_evidence_refs (evidence_ref_id, subject_type, subject_id, source_kind, source_id, information_id, version_id, document_id, url, title, published_at, locator, created_at) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
  .bind(`${subjectId}:evidence:${index + 1}`, subjectType, subjectId, ref.sourceKind, ref.sourceId ?? null, ref.informationId ?? null, ref.versionId ?? null, ref.documentId ?? null, ref.url ?? null, ref.title ?? null, ref.publishedAt === undefined ? null : String(ref.publishedAt), ref.locator ?? null, createdAt)); }
async function runInsert(db: D1Database, table: string, recordId: string, statements: D1PreparedStatement[]): Promise<ResearchOperatingMarketWriteResult> { try { await db.batch(statements); return { state: "saved", recordId, reason: null }; } catch (error) { if (missing(error, table)) return { state: "unavailable", recordId, reason: "storage_not_initialized" }; throw error; } }
